
import java.util.*;

/**
 * A class to represent a graph
 */
public class Graph {
    private Map<String, Vertex> vertices;

    /**
     * Create a new graph.
     */
    public Graph() {
        vertices = new HashMap<>();
    }

    /**
     * Add a new vertex to the graph.
     *
     * @param label the new vertex name.
     */
    void addVertex(String label) {
        vertices.putIfAbsent(label, new Vertex(label));
    }

    /**
     * Remove a vertex from the graph.
     *
     * @param label the vertex name to remove.
     */
    void removeVertex(String label) {
        Vertex v = vertices.remove(label);
        if (v != null) {
            vertices.values().forEach(adjacentVertices -> adjacentVertices.remove(v));
        }
    }

    /**
     * Add an edge to the graph.
     *
     * @param label1 the first vertex name.
     * @param label2 the second vertex name.
     */
    void addEdge(String label1, String label2) {
        Vertex v1 = vertices.get(label1);
        Vertex v2 = vertices.get(label2);
        if (v1 != null && v2 != null) {
            v1.addAdjacentVertex(v2);
            v2.addAdjacentVertex(v1);
        }
    }

    /**
     * Remove an edge from the graph.
     *
     * @param label1 the first vertex name.
     * @param label2 the second vertex name.
     */
    void removeEdge(String label1, String label2) {
        Vertex v1 = vertices.get(label1);
        Vertex v2 = vertices.get(label2);
        if (v1 != null && v2 != null) {
            v1.removeAdjacentVertex(v2);
            v2.removeAdjacentVertex(v1);
        }
    }

    /**
     * Initialize the graph with some example vertices and edges.
     */
    void createGraph(int option) {


        switch (option) {
            case 1:
                // Código para la primera versión del grafo
                //____________________________5 Vertices y 6 Arcos_________________________________
                addVertex("Bob");
                addVertex("Alice");
                addVertex("Mark");
                addVertex("Rob");
                addVertex("Maria");
                addEdge("Bob", "Alice");
                addEdge("Bob", "Maria");
                addEdge("Alice", "Mark");
                addEdge("Rob", "Mark");
                addEdge("Alice", "Maria");
                addEdge("Rob", "Maria");
                break;
            case 2:
                // Código para la segunda versión del grafo
                //____________________________________10 Vertices y 12 Arcos__________________________________
                addVertex("Bob");
                addVertex("Alice");
                addVertex("Mark");
                addVertex("Rob");
                addVertex("Maria");
                addVertex("John");
                addVertex("Emily");
                addVertex("David");
                addVertex("Sarah");
                addVertex("Michael");
                addEdge("Bob", "Alice");
                addEdge("Bob", "Rob");
                addEdge("Alice", "Rob");
                addEdge("Rob", "Maria");
                addEdge("Alice", "Maria");
                addEdge("Bob", "Maria");
                addEdge("Mark", "John");
                addEdge("John", "Emily");
                addEdge("Mark", "David");
                addEdge("David", "Sarah");
                addEdge("María", "Bob");
                addEdge("Sarah", "Michael");
                break;
            case 3:
                // Código para la tercera versión del grafo
                //_______________________________20 Vertices y 20 Arcos_________________________________
                addVertex("Bob");
                addVertex("Alice");
                addVertex("Mark");
                addVertex("Rob");
                addVertex("Maria");
                addVertex("John");
                addVertex("Emily");
                addVertex("David");
                addVertex("Sarah");
                addVertex("Michael");
                addVertex("Laura");
                addVertex("Daniel");
                addVertex("Jennifer");
                addVertex("Chris");
                addVertex("Jessica");
                addVertex("Matthew");
                addVertex("Nicole");
                addVertex("Ryan");
                addVertex("Elizabeth");
                addVertex("Kevin");
                addEdge("Bob", "Alice");
                addEdge("Bob", "Rob");
                addEdge("Alice", "Rob");
                addEdge("Rob", "Maria");
                addEdge("Alice", "Maria");
                addEdge("Bob", "Maria");
                addEdge("Bob", "John");
                addEdge("John", "Alice");
                addEdge("John", "Rob");
                addEdge("David", "Sarah");
                addEdge("John", "Maria");
                addEdge("Sarah", "Michael");
                addEdge("Laura", "Daniel");
                addEdge("Daniel", "Jennifer");
                addEdge("Laura", "Chris");
                addEdge("Chris", "Jessica");
                addEdge("Jessica", "Matthew");
                addEdge("Matthew", "Nicole");
                addEdge("Nicole", "Ryan");
                addEdge("Ryan", "Elizabeth");
                addEdge("Elizabeth", "Kevin");
                break;
            case 4:
                addVertex("Bob");
                addVertex("Alice");
                addVertex("Mark");
                addVertex("Rob");
                addVertex("Maria");
                addVertex("John");
                addVertex("Emily");
                addVertex("David");
                addVertex("Sarah");
                addVertex("Michael");
                addVertex("Laura");
                addVertex("Daniel");
                addVertex("Jennifer");
                addVertex("Chris");
                addVertex("Jessica");
                addVertex("Matthew");
                addVertex("Nicole");
                addVertex("Ryan");
                addVertex("Elizabeth");
                addVertex("Kevin");

                addEdge("Bob", "Alice");
                addEdge("Bob", "Rob");
                addEdge("Bob", "Maria");
                addEdge("Alice", "Rob");
                addEdge("Alice", "Maria");
                addEdge("Mark", "John");
                addEdge("Mark", "David");
                addEdge("Mark", "Daniel");
                addEdge("Rob", "Maria");
                addEdge("Rob", "John");
                addEdge("John", "Emily");
                addEdge("John", "Sarah");
                addEdge("John", "Michael");
                addEdge("Emily", "David");
                addEdge("Emily", "Laura");
                addEdge("Emily", "Chris");
                addEdge("David", "Sarah");
                addEdge("David", "Michael");
                addEdge("Sarah", "Laura");
                addEdge("Sarah", "Daniel");
                addEdge("Sarah", "Chris");
                addEdge("Michael", "Laura");
                addEdge("Michael", "Daniel");
                addEdge("Laura", "Daniel");
                addEdge("Laura", "Chris");
                addEdge("Laura", "Jessica");
                addEdge("Daniel", "Chris");
                addEdge("Daniel", "Jessica");
                addEdge("Chris", "Jessica");
                addEdge("Sarah", "Michael");

                break;
            case 5:
                addVertex("Bob");
                addVertex("Alice");
                addVertex("Mark");
                addVertex("Rob");
                addVertex("Maria");
                addVertex("John");
                addVertex("Emily");
                addVertex("David");
                addVertex("Sarah");
                addVertex("Michael");
                addVertex("Laura");
                addVertex("Daniel");
                addVertex("Jennifer");
                addVertex("Chris");
                addVertex("Jessica");
                addVertex("Matthew");
                addVertex("Nicole");
                addVertex("Ryan");
                addVertex("Elizabeth");
                addVertex("Kevin");

                addEdge("Bob", "Alice");
                addEdge("Bob", "Mark");
                addEdge("Bob", "Rob");
                addEdge("Bob", "Maria");
                addEdge("Bob", "John");
                addEdge("Bob", "Emily");
                addEdge("Bob", "David");
                addEdge("Bob", "Sarah");
                addEdge("Bob", "Michael");
                addEdge("Bob", "Laura");
                addEdge("Bob", "Daniel");
                addEdge("Bob", "Jennifer");
                addEdge("Bob", "Chris");
                addEdge("Bob", "Jessica");
                addEdge("Bob", "Matthew");
                addEdge("Bob", "Nicole");
                addEdge("Bob", "Ryan");
                addEdge("Bob", "Elizabeth");
                addEdge("Bob", "Kevin");
                addEdge("Alice", "Mark");
                addEdge("Alice", "Rob");
                addEdge("Alice", "Maria");
                addEdge("Alice", "John");
                addEdge("Alice", "Emily");
                addEdge("Alice", "David");
                addEdge("Alice", "Sarah");
                addEdge("Alice", "Michael");
                addEdge("Alice", "Laura");
                addEdge("Alice", "Daniel");
                addEdge("Alice", "Jennifer");
                addEdge("Alice", "Chris");
                addEdge("Alice", "Jessica");
                addEdge("Alice", "Matthew");
                addEdge("Alice", "Nicole");
                addEdge("Alice", "Ryan");
                addEdge("Alice", "Elizabeth");
                addEdge("Alice", "Kevin");

                break;
            case 6:
                addVertex("Bob");
                addVertex("Alice");
                addVertex("Mark");
                addVertex("Rob");
                addVertex("Maria");
                addVertex("John");
                addVertex("Emily");
                addVertex("David");
                addVertex("Sarah");
                addVertex("Michael");
                addVertex("Laura");
                addVertex("Daniel");
                addVertex("Jennifer");
                addVertex("Chris");
                addVertex("Jessica");
                addVertex("Matthew");
                addVertex("Nicole");
                addVertex("Ryan");
                addVertex("Elizabeth");
                addVertex("Kevin");

                addEdge("Bob", "Alice");
                addEdge("Bob", "Mark");
                addEdge("Bob", "Rob");
                addEdge("Bob", "Maria");
                addEdge("Bob", "John");
                addEdge("Bob", "Emily");
                addEdge("Bob", "David");
                addEdge("Bob", "Sarah");
                addEdge("Bob", "Michael");
                addEdge("Bob", "Laura");
                addEdge("Bob", "Daniel");
                addEdge("Bob", "Jennifer");
                addEdge("Bob", "Chris");
                addEdge("Bob", "Jessica");
                addEdge("Bob", "Matthew");
                addEdge("Bob", "Nicole");
                addEdge("Bob", "Ryan");
                addEdge("Bob", "Elizabeth");
                addEdge("Bob", "Kevin");
                addEdge("Alice", "Mark");
                addEdge("Alice", "Rob");
                addEdge("Alice", "Maria");
                addEdge("Alice", "John");
                addEdge("Alice", "Emily");
                addEdge("Alice", "David");
                addEdge("Alice", "Sarah");
                addEdge("Alice", "Michael");
                addEdge("Alice", "Laura");
                addEdge("Alice", "Daniel");
                addEdge("Alice", "Jennifer");
                addEdge("Alice", "Chris");
                addEdge("Alice", "Jessica");
                addEdge("Alice", "Matthew");
                addEdge("Alice", "Nicole");
                addEdge("Alice", "Ryan");
                addEdge("Alice", "Elizabeth");
                addEdge("Alice", "Kevin");
                addEdge("Mark", "Rob");
                addEdge("Mark", "Maria");
                addEdge("Mark", "John");
                addEdge("Mark", "Emily");
                addEdge("Mark", "David");
                addEdge("Mark", "Sarah");
                addEdge("Mark", "Michael");
                addEdge("Mark", "Laura");
                addEdge("Mark", "Daniel");
                addEdge("Mark", "Jennifer");
                addEdge("Mark", "Chris");
                addEdge("Mark", "Jessica");
                addEdge("Mark", "Matthew");


                break;
            case 7:
                addVertex("Bob");
                addVertex("Alice");
                addVertex("Mark");
                addVertex("Rob");
                addVertex("Maria");
                addVertex("John");
                addVertex("Emily");
                addVertex("David");
                addVertex("Sarah");
                addVertex("Michael");
                addVertex("Laura");
                addVertex("Daniel");
                addVertex("Jennifer");
                addVertex("Chris");
                addVertex("Jessica");
                addVertex("Matthew");
                addVertex("Nicole");
                addVertex("Ryan");
                addVertex("Elizabeth");
                addVertex("Kevin");

                addEdge("Bob", "Alice");
                addEdge("Bob", "Mark");
                addEdge("Bob", "Rob");
                addEdge("Bob", "Maria");
                addEdge("Bob", "John");
                addEdge("Bob", "Emily");
                addEdge("Bob", "David");
                addEdge("Bob", "Sarah");
                addEdge("Bob", "Michael");
                addEdge("Bob", "Laura");
                addEdge("Bob", "Daniel");
                addEdge("Bob", "Jennifer");
                addEdge("Bob", "Chris");
                addEdge("Bob", "Jessica");
                addEdge("Bob", "Matthew");
                addEdge("Bob", "Nicole");
                addEdge("Bob", "Ryan");
                addEdge("Bob", "Elizabeth");
                addEdge("Bob", "Kevin");
                addEdge("Alice", "Mark");
                addEdge("Alice", "Rob");
                addEdge("Alice", "Maria");
                addEdge("Alice", "John");
                addEdge("Alice", "Emily");
                addEdge("Alice", "David");
                addEdge("Alice", "Sarah");
                addEdge("Alice", "Michael");
                addEdge("Alice", "Laura");
                addEdge("Alice", "Daniel");
                addEdge("Alice", "Jennifer");
                addEdge("Alice", "Chris");
                addEdge("Alice", "Jessica");
                addEdge("Alice", "Matthew");
                addEdge("Alice", "Nicole");
                addEdge("Alice", "Ryan");
                addEdge("Alice", "Elizabeth");
                addEdge("Alice", "Kevin");
                addEdge("Mark", "Rob");
                addEdge("Mark", "Maria");
                addEdge("Mark", "John");
                addEdge("Mark", "Emily");
                addEdge("Mark", "David");
                addEdge("Mark", "Sarah");
                addEdge("Mark", "Michael");
                addEdge("Mark", "Laura");
                addEdge("Mark", "Daniel");
                addEdge("Mark", "Jennifer");
                addEdge("Mark", "Chris");
                addEdge("Mark", "Jessica");
                addEdge("Mark", "Matthew");
                addEdge("Mark", "Nicole");
                addEdge("Mark", "Ryan");
                addEdge("Mark", "Elizabeth");
                addEdge("Mark", "Kevin");
                addEdge("Rob", "Maria");
                addEdge("Rob", "John");
                addEdge("Rob", "Emily");
                addEdge("Rob", "David");
                addEdge("Rob", "Sarah");
                addEdge("Rob", "Michael");
                addEdge("Rob", "Laura");
                addEdge("Rob", "Daniel");
                addEdge("Rob", "Jennifer");
                addEdge("Rob", "Chris");
                addEdge("Rob", "Jessica");
                addEdge("Rob", "Matthew");
                addEdge("Rob", "Nicole");
                addEdge("Rob", "Ryan");
                addEdge("Rob", "Elizabeth");
                addEdge("Rob", "Kevin");
                addEdge("Maria", "John");
                addEdge("Maria", "Emily");
                addEdge("Maria", "David");
                addEdge("Maria", "Sarah");
                addEdge("Maria", "Michael");
                addEdge("Maria", "Laura");
                addEdge("Maria", "Daniel");
                addEdge("Maria", "Jennifer");
                addEdge("Maria", "Chris");
                addEdge("Maria", "Jessica");

                break;

            case 8:
                addVertex("Bob");
                addVertex("Alice");
                addVertex("Mark");
                addVertex("Rob");
                addVertex("Maria");
                addVertex("John");
                addVertex("Emily");
                addVertex("David");
                addVertex("Sarah");
                addVertex("Michael");
                addVertex("Laura");
                addVertex("Daniel");
                addVertex("Jennifer");
                addVertex("Chris");
                addVertex("Jessica");
                addVertex("Matthew");
                addVertex("Nicole");
                addVertex("Ryan");
                addVertex("Elizabeth");
                addVertex("Kevin");
                addVertex("Sophia");
                addVertex("Jacob");
                addVertex("Olivia");
                addVertex("Emma");
                addVertex("Kenia");
                addVertex("Ethan");
                addVertex("Ava");
                addVertex("Mia");
                addVertex("Alexander");
                addVertex("William");
                addVertex("James");
                addVertex("Elijah");
                addVertex("Benjamin");
                addVertex("Lucas");
                addVertex("Henry");
                addVertex("Charlotte");
                addVertex("Amelia");
                addVertex("Harper");
                addVertex("Evelyn");
                addVertex("Carmen");

                addEdge("Bob", "Alice");
                addEdge("Bob", "Mark");
                addEdge("Bob", "Rob");
                addEdge("Bob", "Maria");
                addEdge("Bob", "John");
                addEdge("Bob", "Emily");
                addEdge("Bob", "David");
                addEdge("Bob", "Sarah");
                addEdge("Bob", "Michael");
                addEdge("Bob", "Laura");
                addEdge("Bob", "Daniel");
                addEdge("Bob", "Jennifer");
                addEdge("Bob", "Chris");
                addEdge("Bob", "Jessica");
                addEdge("Bob", "Matthew");
                addEdge("Bob", "Nicole");
                addEdge("Bob", "Ryan");
                addEdge("Bob", "Elizabeth");
                addEdge("Bob", "Kevin");
                addEdge("Bob", "Sophia");
                addEdge("Bob", "Jacob");
                addEdge("Bob", "Olivia");
                addEdge("Bob", "Emma");
                addEdge("Bob", "Kenia");
                addEdge("Bob", "Ethan");
                addEdge("Bob", "Ava");
                addEdge("Bob", "Mia");
                addEdge("Bob", "Alexander");
                addEdge("Bob", "William");
                addEdge("Bob", "James");
                addEdge("Bob", "Elijah");
                addEdge("Bob", "Benjamin");
                addEdge("Bob", "Lucas");
                addEdge("Bob", "Henry");
                addEdge("Bob", "Charlotte");
                addEdge("Bob", "Amelia");
                addEdge("Bob", "Harper");
                addEdge("Alice", "Mark");
                addEdge("Alice", "Rob");
                addEdge("Alice", "Maria");
                addEdge("Alice", "John");
                addEdge("Alice", "Emily");
                addEdge("Alice", "David");
                addEdge("Alice", "Sarah");
                addEdge("Alice", "Michael");
                addEdge("Alice", "Laura");
                addEdge("Alice", "Daniel");
                addEdge("Alice", "Jennifer");
                addEdge("Alice", "Chris");
                addEdge("Alice", "Jessica");
                addEdge("Alice", "Matthew");
                addEdge("Alice", "Nicole");
                addEdge("Alice", "Ryan");
                addEdge("Alice", "Elizabeth");
                addEdge("Alice", "Kevin");
                addEdge("Alice", "Sophia");
                addEdge("Alice", "Jacob");
                addEdge("Alice", "Olivia");
                addEdge("Alice", "Emma");
                addEdge("Alice", "Michael");
                addEdge("Alice", "Ethan");
                addEdge("Alice", "Ava");
                addEdge("Alice", "Mia");
                addEdge("Alice", "Alexander");
                addEdge("Alice", "William");
                addEdge("Alice", "James");
                addEdge("Alice", "Elijah");
                addEdge("Alice", "Benjamin");
                addEdge("Alice", "Lucas");
                addEdge("Alice", "Henry");
                addEdge("Alice", "Charlotte");
                addEdge("Alice", "Amelia");
                addEdge("Alice", "Harper");
                addEdge("Mark", "Rob");
                addEdge("Mark", "Maria");
                addEdge("Mark", "John");
                addEdge("Mark", "Emily");
                addEdge("Mark", "David");
                addEdge("Mark", "Sarah");
                addEdge("Mark", "Michael");
                addEdge("Mark", "Laura");
                addEdge("Mark", "Daniel");
                addEdge("Mark", "Jennifer");
                addEdge("Mark", "Chris");
                addEdge("Mark", "Jessica");
                addEdge("Mark", "Matthew");
                addEdge("Mark", "Nicole");
                addEdge("Mark", "Ryan");
                addEdge("Mark", "Elizabeth");
                addEdge("Mark", "Kevin");
                addEdge("Mark", "Sophia");
                addEdge("Mark", "Jacob");
                addEdge("Mark", "Olivia");
                addEdge("Mark", "Emma");
                addEdge("Mark", "Michael");
                addEdge("Mark", "Ethan");
                addEdge("Mark", "Ava");
                addEdge("Mark", "Mia");
                addEdge("Mark", "Alexander");
                addEdge("Mark", "William");
                addEdge("Mark", "James");
                addEdge("Mark", "Elijah");
                addEdge("Mark", "Benjamin");
                addEdge("Mark", "Lucas");
                addEdge("Mark", "Henry");
                addEdge("Mark", "Charlotte");
                addEdge("Mark", "Amelia");
                addEdge("Mark", "Harper");
                addEdge("Maria", "John");
                addEdge("Maria", "Emily");
                addEdge("Maria", "David");
                addEdge("Maria", "Sarah");
                addEdge("Maria", "Michael");
                addEdge("Maria", "Laura");
                addEdge("Maria", "Daniel");
                addEdge("Maria", "Jennifer");
                addEdge("Maria", "Chris");
                addEdge("Maria", "Jessica");
                addEdge("Maria", "Matthew");
                addEdge("Maria", "Nicole");
                break;

            case 9:
                addVertex("Bob");
                addVertex("Alice");
                addVertex("Mark");
                addVertex("Rob");
                addVertex("Maria");
                addVertex("John");
                addVertex("Emily");
                addVertex("David");
                addVertex("Sarah");
                addVertex("Michael");
                addVertex("Laura");
                addVertex("Daniel");
                addVertex("Jennifer");
                addVertex("Chris");
                addVertex("Jessica");
                addVertex("Matthew");
                addVertex("Nicole");
                addVertex("Ryan");
                addVertex("Elizabeth");
                addVertex("Kevin");
                addVertex("Sophia");
                addVertex("Jacob");
                addVertex("Olivia");
                addVertex("Emma");
                addVertex("Marcos");
                addVertex("Ethan");
                addVertex("Ava");
                addVertex("Mia");
                addVertex("Alexander");
                addVertex("William");
                addVertex("James");
                addVertex("Elijah");
                addVertex("Benjamin");
                addVertex("Lucas");
                addVertex("Henry");
                addVertex("Charlotte");
                addVertex("Amelia");
                addVertex("Harper");
                addVertex("Evelyn");
                addVertex("Carmen");
                addVertex("Luis");
                addVertex("Carlos");
                addVertex("Pedro");
                addVertex("Juan");
                addVertex("Pablo");
                addVertex("Santiago");
                addVertex("Diego");
                addVertex("Manuel");
                addVertex("Javier");
                addVertex("Ricardo");
                addVertex("Fernando");
                addVertex("Jorge");
                addVertex("Alejandro");
                addVertex("Gustavo");
                addVertex("Miguel");
                addVertex("Rafael");
                addVertex("Arturo");
                addVertex("Hector");
                addVertex("Oscar");
                addVertex("Andres");

                addEdge("Bob", "Mark");
                addEdge("Bob", "Rob");
                addEdge("Bob", "Maria");
                addEdge("Bob", "John");
                addEdge("Bob", "Emily");
                addEdge("Bob", "David");
                addEdge("Bob", "Sarah");
                addEdge("Bob", "Michael");
                addEdge("Bob", "Laura");
                addEdge("Bob", "Daniel");
                addEdge("Bob", "Jennifer");
                addEdge("Bob", "Chris");
                addEdge("Bob", "Ethan");
                addEdge("Bob", "Ava");
                addEdge("Bob", "Mia");
                addEdge("Bob", "Alexander");
                addEdge("Bob", "William");
                addEdge("Bob", "James");
                addEdge("Bob", "Elijah");
                addEdge("Bob", "Benjamin");
                addEdge("Bob", "Lucas");
                addEdge("Bob", "Henry");
                addEdge("Bob", "Charlotte");
                addEdge("Bob", "Amelia");
                addEdge("Bob", "Harper");
                addEdge("Bob", "Evelyn");
                addEdge("Bob", "Carmen");
                addEdge("Bob", "Luis");
                addEdge("Bob", "Carlos");
                addEdge("Bob", "Pedro");
                addEdge("Bob", "Juan");
                addEdge("Bob", "Pablo");
                addEdge("Bob", "Santiago");
                addEdge("Bob", "Diego");
                addEdge("Bob", "Manuel");
                addEdge("Bob", "Javier");
                addEdge("Bob", "Ricardo");
                addEdge("Bob", "Fernando");
                addEdge("Bob", "Jorge");
                addEdge("Bob", "Alejandro");
                addEdge("Bob", "Gustavo");
                addEdge("Bob", "Miguel");
                addEdge("Bob", "Rafael");
                addEdge("Bob", "Arturo");
                addEdge("Bob", "Hector");
                addEdge("Bob", "Oscar");
                addEdge("Bob", "Andres");
                addEdge("Alice", "Mark");
                addEdge("Alice", "Rob");
                addEdge("Alice", "Maria");
                addEdge("Alice", "John");
                addEdge("Alice", "Emily");
                addEdge("Alice", "David");
                addEdge("Alice", "Sarah");
                addEdge("Alice", "Michael");
                addEdge("Alice", "Laura");
                addEdge("Alice", "Daniel");
                addEdge("Alice", "Jennifer");
                addEdge("Alice", "Chris");
                addEdge("Alice", "Jessica");
                addEdge("Alice", "Matthew");
                addEdge("Alice", "Nicole");
                addEdge("Alice", "Ryan");
                addEdge("Alice", "Elizabeth");
                addEdge("Alice", "Kevin");
                addEdge("Alice", "Sophia");
                addEdge("Alice", "Jacob");
                addEdge("Alice", "Olivia");
                addEdge("Alice", "Emma");
                addEdge("Alice", "Marcos");
                addEdge("Alice", "Ethan");
                addEdge("Alice", "Ava");
                addEdge("Alice", "Mia");
                addEdge("Alice", "Alexander");
                addEdge("Alice", "William");
                addEdge("Alice", "James");
                addEdge("Alice", "Elijah");
                addEdge("Alice", "Benjamin");
                addEdge("Alice", "Lucas");
                addEdge("Alice", "Henry");
                addEdge("Alice", "Charlotte");
                addEdge("Alice", "Amelia");
                addEdge("Alice", "Harper");
                addEdge("Alice", "Evelyn");
                addEdge("Alice", "Carmen");
                addEdge("Alice", "Luis");
                addEdge("Alice", "Carlos");
                addEdge("Alice", "Pedro");
                addEdge("Alice", "Juan");
                addEdge("Alice", "Pablo");
                addEdge("Alice", "Santiago");
                addEdge("Alice", "Diego");
                addEdge("Alice", "Manuel");
                addEdge("Alice", "Javier");
                addEdge("Alice", "Ricardo");
                addEdge("Alice", "Fernando");
                addEdge("Alice", "Jorge");
                addEdge("Alice", "Alejandro");
                addEdge("Alice", "Gustavo");
                addEdge("Alice", "Miguel");
                addEdge("Alice", "Rafael");
                addEdge("Alice", "Arturo");
                addEdge("Alice", "Hector");
                addEdge("Alice", "Oscar");
                addEdge("Alice", "Andres");
                addEdge("Mark", "Rob");
                addEdge("Mark", "Maria");
                addEdge("Mark", "John");
                addEdge("Mark", "Emily");
                addEdge("Mark", "David");
                addEdge("Mark", "Sarah");
                addEdge("Mark", "Michael");
                addEdge("Mark", "Laura");
                addEdge("Mark", "Daniel");
                addEdge("Mark", "Jennifer");
                addEdge("Mark", "Chris");
                addEdge("Mark", "Jessica");
                addEdge("Mark", "Matthew");
                addEdge("Mark", "Nicole");
                addEdge("Mark", "Ryan");
                addEdge("Mark", "Elizabeth");
                addEdge("Mark", "Kevin");
                addEdge("Mark", "Sophia");
                addEdge("Mark", "Jacob");
                addEdge("Mark", "Olivia");
                addEdge("Mark", "Emma");
                addEdge("Mark", "Marcos");
                addEdge("Mark", "Ethan");
                addEdge("Mark", "Ava");
                addEdge("Mark", "Mia");
                addEdge("Mark", "Alexander");
                addEdge("Mark", "William");
                addEdge("Mark", "James");
                addEdge("Mark", "Elijah");
                addEdge("Mark", "Benjamin");
                addEdge("Mark", "Lucas");
                addEdge("Mark", "Henry");
                addEdge("Mark", "Charlotte");
                addEdge("Mark", "Amelia");
                addEdge("Mark", "Harper");
                addEdge("Mark", "Evelyn");
                addEdge("Mark", "Santiago");
                addEdge("Mark", "Diego");
                addEdge("Mark", "Manuel");
                addEdge("Mark", "Javier");
                addEdge("Mark", "Ricardo");
                addEdge("Mark", "Fernando");
                addEdge("Mark", "Jorge");
                addEdge("Mark", "Alejandro");
                addEdge("Mark", "Gustavo");
                addEdge("Mark", "Miguel");
                addEdge("Mark", "Rafael");
                addEdge("Mark", "Arturo");
                addEdge("Mark", "Hector");
                addEdge("Mark", "Oscar");
                addEdge("Mark", "Andres");
                addEdge("Rob", "Maria");
                addEdge("Rob", "Michael");
                addEdge("Rob", "Laura");
                addEdge("Rob", "Daniel");
                addEdge("Rob", "Jennifer");
                addEdge("Rob", "Chris");
                addEdge("Rob", "Jessica");
                addEdge("Rob", "Matthew");
                addEdge("Rob", "Nicole");
                addEdge("Rob", "Ryan");
                addEdge("Rob", "Elizabeth");
                addEdge("Rob", "Kevin");
                addEdge("Rob", "Sophia");
                addEdge("Rob", "Jacob");
                addEdge("Rob", "Olivia");
                addEdge("Rob", "Emma");
                addEdge("Rob", "Marcos");
                addEdge("Rob", "Ethan");
                addEdge("Rob", "Ava");
                addEdge("Rob", "Mia");
                addEdge("Rob", "Alexander");
                addEdge("Rob", "William");
                addEdge("Rob", "James");
                addEdge("Rob", "Elijah");
                addEdge("Rob", "Benjamin");
                addEdge("Rob", "Lucas");
                addEdge("Rob", "Henry");
                addEdge("Rob", "Charlotte");
                addEdge("Rob", "Amelia");
                addEdge("Rob", "Harper");
                addEdge("Rob", "Evelyn");
                addEdge("Rob", "Carmen");
                addEdge("Rob", "Luis");
                addEdge("Rob", "Carlos");
                addEdge("Rob", "Pedro");
                addEdge("Rob", "Juan");
                addEdge("Rob", "Pablo");
                addEdge("Rob", "Santiago");
                addEdge("Rob", "Diego");
                addEdge("Rob", "Manuel");
                addEdge("Rob", "Javier");
                addEdge("Rob", "Ricardo");
                addEdge("Rob", "Fernando");
                addEdge("Rob", "Jorge");
                addEdge("Rob", "Alejandro");
                addEdge("Rob", "Gustavo");
                addEdge("Rob", "Miguel");
                addEdge("Maria", "David");
                addEdge("Maria", "Sarah");
                addEdge("Maria", "Michael");
                addEdge("Maria", "Laura");
                addEdge("Maria", "Daniel");
                addEdge("Maria", "Jennifer");
                addEdge("Maria", "Chris");
                addEdge("Maria", "Jessica");
                addEdge("Maria", "Matthew");
                addEdge("Maria", "Nicole");
                addEdge("Maria", "Ryan");
                addEdge("Maria", "Elizabeth");
                addEdge("Maria", "Kevin");
                addEdge("Maria", "Sophia");
                addEdge("Maria", "Jacob");
                addEdge("Maria", "Olivia");
                addEdge("Maria", "Emma");
                addEdge("Maria", "Marcos");
                addEdge("Maria", "Ethan");
                addEdge("Maria", "Ava");
                addEdge("Maria", "Mia");
                addEdge("Maria", "Alexander");
                addEdge("Maria", "William");
                addEdge("Maria", "James");
                addEdge("Maria", "Elijah");
                addEdge("Maria", "Benjamin");
                addEdge("Maria", "Lucas");
                addEdge("Maria", "Henry");
                addEdge("Maria", "Charlotte");
                addEdge("Maria", "Amelia");
                addEdge("Maria", "Harper");
                addEdge("Maria", "Evelyn");
                addEdge("Maria", "Carmen");
                addEdge("Maria", "Luis");
                addEdge("Maria", "Carlos");
                addEdge("Maria", "Pedro");
                addEdge("Maria", "Juan");

                break;

            case 10:
                addVertex("Bob");
                addVertex("Alice");
                addVertex("Mark");
                addVertex("Rob");
                addVertex("Maria");
                addVertex("John");
                addVertex("Emily");
                addVertex("David");
                addVertex("Sarah");
                addVertex("Michael");
                addVertex("Laura");
                addVertex("Daniel");
                addVertex("Jennifer");
                addVertex("Chris");
                addVertex("Jessica");
                addVertex("Matthew");
                addVertex("Nicole");
                addVertex("Ryan");
                addVertex("Elizabeth");
                addVertex("Kevin");
                addVertex("Alex");
                addVertex("Sophia");
                addVertex("William");
                addVertex("Isabella");
                addVertex("Ethan");
                addVertex("Ava");
                addVertex("James");
                addVertex("Olivia");
                addVertex("Benjamin");
                addVertex("Amelia");
                addVertex("Lucas");
                addVertex("Mia");
                addVertex("Henry");
                addVertex("Charlotte");
                addVertex("Alexander");
                addVertex("Elijah");
                addVertex("Harper");
                addVertex("Evelyn");
                addVertex("Abigail");
                addVertex("Jackson");
                addVertex("Sebastian");
                addVertex("Aiden");
                addVertex("Avery");
                addVertex("Sofia");
                addVertex("Samuel");
                addVertex("Camila");
                addVertex("Ella");
                addVertex("Joseph");
                addVertex("Madison");
                addVertex("Gabriel");
                addVertex("Scarlett");
                addVertex("Dylan");
                addVertex("Grace");
                addVertex("Luke");
                addVertex("Chloe");
                addVertex("Anthony");
                addVertex("Penelope");
                addVertex("Isaac");
                addVertex("Layla");
                addVertex("Christopher");
                addVertex("Riley");
                addVertex("Andrew");
                addVertex("Zoey");
                addVertex("Joshua");
                addVertex("Nora");
                addVertex("Charles");
                addVertex("Lily");
                addVertex("Carter");
                addVertex("Hannah");
                addVertex("Lincoln");
                addVertex("Aria");
                addVertex("Nathan");
                addVertex("Eleanor");
                addVertex("Violet");
                addVertex("Adam");
                addVertex("Savannah");
                addVertex("Lorera");
                addVertex("Nahúm");
                addVertex("Gary");
                addVertex("Marlon");

                addEdge("Bob", "Alice");
                addEdge("Bob", "Mark");
                addEdge("Bob", "Rob");
                addEdge("Bob", "John");
                addEdge("Bob", "Emily");
                addEdge("Bob", "David");
                addEdge("Bob", "Sarah");
                addEdge("Bob", "Michael");
                addEdge("Bob", "Laura");
                addEdge("Bob", "Daniel");
                addEdge("Bob", "Jennifer");
                addEdge("Bob", "Chris");
                addEdge("Bob", "Jessica");
                addEdge("Bob", "Ryan");
                addEdge("Bob", "Elizabeth");
                addEdge("Bob", "Lorena");
                addEdge("Bob", "Nahúm");
                addEdge("Bob", "Gary");
                addEdge("Bob", "Marlon");
                addEdge("Kevin", "Lorena");
                addEdge("Kevin", "Nahúm");
                addEdge("Kevin", "Gary");
                addEdge("Kevin", "Marlon");
                addEdge("Kevin", "Bob");
                addEdge("Kevin", "Alice");
                addEdge("Alice", "Mark");
                addEdge("Alice", "Emily");
                addEdge("Alice", "David");
                addEdge("Alice", "Sarah");
                addEdge("Alice", "Michael");
                addEdge("Alice", "Laura");
                addEdge("Alice", "Daniel");
                addEdge("Alice", "Jennifer");
                addEdge("Alice", "Chris");
                addEdge("Alice", "Jessica");
                addEdge("Alice", "Ryan");
                addEdge("Alice", "Elizabeth");
                addEdge("Alice", "Lorena");
                addEdge("Alice", "Nahúm");
                addEdge("Alice", "Gary");
                addEdge("Alice", "Marlon");
                addEdge("Mark", "Emily");
                addEdge("Mark", "David");
                addEdge("Mark", "Sarah");
                addEdge("Mark", "Michael");
                addEdge("Mark", "Jennifer");
                addEdge("Mark", "Ryan");
                addEdge("Mark", "Laura");
                addEdge("Mark", "Daniel");
                addEdge("Mark", "Jessica");
                addEdge("Mark", "Elizabeth");
                addEdge("Mark", "Kevin");
                addEdge("Mark", "Lorena");
                addEdge("Mark", "Nahúm");
                addEdge("Mark", "Gary");
                addEdge("Mark", "Marlon");
                addEdge("Kevin", "Emily");
                addEdge("Kevin", "David");
                addEdge("Kevin", "Sarah");
                addEdge("Kevin", "Michael");
                addEdge("Kevin", "Laura");
                addEdge("Kevin", "Daniel");
                addEdge("Kevin", "Jennifer");
                addEdge("Kevin", "Chris");
                addEdge("Kevin", "Jessica");
                addEdge("Ryan", "Kevin");
                addEdge("Elizabeth", "Kevin");
                addEdge("Alexander", "Kevin");
                addEdge("Mia", "Kevin");
                addEdge("Amelia", "Kevin");
                addEdge("Henry", "Kevin");
                addEdge("Benjamin", "Kevin");
                addEdge("Lucas", "Kevin");
                addEdge("Evelyn", "Kevin");
                addEdge("Sebastian", "Kevin");
                addEdge("Jackson", "Kevin");
                addEdge("Olivia", "Kevin");
                addEdge("Abigail", "Kevin");
                addEdge("Kevin", "Aiden");
                addEdge("Kevin", "Avery");
                addEdge("Kevin", "Sofia");
                addEdge("Kevin", "Samuel");
                addEdge("Kevin", "Camila");
                addEdge("Kevin", "Ella");
                addEdge("Kevin", "Joseph");
                addEdge("Kevin", "Madison");
                addEdge("Kevin", "Gabriel");
                addEdge("Kevin", "Scarlett");
                addEdge("Kevin", "Dylan");
                addEdge("Kevin", "Anthony");
                addEdge("Kevin", "Grace");
                addEdge("Luke", "Kevin");
                addEdge("Chloe", "Kevin");
                addEdge("Penelope", "Kevin");
                addEdge("Isaac", "Kevin");
                addEdge("Layla", "Kevin");
                addEdge("Christopher", "Kevin");
                addEdge("Riley", "Kevin");
                addEdge("Andrew", "Kevin");
                addEdge("Zoey", "Kevin");
                addEdge("Joshua", "Kevin");
                addEdge("Nora", "Kevin");
                addEdge("Charles", "Kevin");
                addEdge("Lily", "Kevin");
                addEdge("Kevin", "Carter");
                addEdge("Kevin", "Hannah");
                addEdge("Kevin", "Lincoln");
                addEdge("Kevin", "Aria");
                addEdge("Kevin", "Nathan");
                addEdge("Kevin", "Eleanor");
                addEdge("Kevin", "Violet");
                addEdge("Kevin", "Adam");
                addEdge("Kevin", "Savannah");
                addEdge("Chris", "Jessica");
                addEdge("Chris", "Ryan");
                addEdge("Chris", "Elizabeth");
                addEdge("Chris", "Mark");
                addEdge("Chris", "Lorena");
                addEdge("Chris", "Nahúm");
                addEdge("Chris", "Gary");
                addEdge("Chris", "Marlon");
                addEdge("Jessica", "Ryan");
                addEdge("Jessica", "Elizabeth");
                addEdge("Jessica", "Hannah");
                addEdge("Jessica", "Nathan");
                addEdge("Jessica", "Lily");
                addEdge("Jessica", "Aria");
                addEdge("Jessica", "Joseph");
                addEdge("Jessica", "Nora");
                addEdge("Jessica", "Charles");
                addEdge("Jessica", "Carter");
                addEdge("Jessica", "Emily");
                addEdge("Jessica", "David");
                addEdge("Jessica", "Sarah");
                addEdge("Jessica", "Michael");
                addEdge("Jessica", "Laura");
                addEdge("Jessica", "Daniel");
                addEdge("Jessica", "Jennifer");
                addEdge("Jessica", "Adam");
                addEdge("Jessica", "Eleanor");
                addEdge("Jessica", "Violet");
                addEdge("Jessica", "Savannah");
                addEdge("Jessica", "Lorena");
                addEdge("Jessica", "Nahúm");
                addEdge("Jessica", "Gary");
                addEdge("Jessica", "Marlon");
                addEdge("Anthony", "Jessica");
                addEdge("Penelope", "Jessica");
                addEdge("Penelope", "Jessica");
                addEdge("Isaac", "Jessica");
                addEdge("Christopher", "Jessica");
                addEdge("Layla", "Jessica");
                addEdge("Grace", "Jessica");
                addEdge("Matthew", "Mark");
                addEdge("Matthew", "Savannah");
                addEdge("Matthew", "Emily");
                addEdge("Matthew", "David");
                addEdge("Matthew", "Sarah");
                addEdge("Matthew", "Michael");
                addEdge("Matthew", "Laura");
                addEdge("Matthew", "Daniel");
                addEdge("Matthew", "Jennifer");
                addEdge("Matthew", "Ryan");
                addEdge("Matthew", "Elizabeth");
                addEdge("Chris", "Matthew");
                addEdge("Carter", "Matthew");
                addEdge("Hannah", "Matthew");
                addEdge("Lincoln", "Matthew");
                addEdge("Aria", "Matthew");
                addEdge("Nathan", "Matthew");
                addEdge("Eleanor", "Matthew");
                addEdge("Violet", "Matthew");
                addEdge("Adam", "Matthew");
                addEdge("Matthew", "Nora");
                addEdge("Matthew", "Charles");
                addEdge("Matthew", "Joshua");
                addEdge("Matthew", "Lily");
                addEdge("Jessica", "Matthew");
                addEdge("Riley", "Matthew");
                addEdge("Mark", "Matthew");
                addEdge("Alice", "Matthew");
                addEdge("Bob", "Matthew");
                addEdge("Matthew", "Andrew");
                addEdge("Matthew", "Zoey");
                addEdge("Matthew", "Kevin");
                addEdge("Matthew", "Lorena");
                addEdge("Matthew", "Nahúm");
                addEdge("Matthew", "Gary");
                addEdge("Matthew", "Marlon");
                addEdge("Nicole", "Mark");
                addEdge("Nicole", "Emily");
                addEdge("Nicole", "David");
                addEdge("Nicole", "Sarah");
                addEdge("Nicole", "Michael");
                addEdge("Nicole", "Laura");
                addEdge("Nicole", "Daniel");
                addEdge("Nicole", "Ryan");
                addEdge("Nicole", "Elizabeth");
                addEdge("Nicole", "Kevin");
                addEdge("Chris", "Nicole");
                addEdge("Jennifer", "Nicole");
                addEdge("Nicole", "Ryan");
                addEdge("Matthew", "Nicole");
                addEdge("Jessica", "Nicole");
                addEdge("Savannah", "Nicole");
                addEdge("Alice", "Nicole");
                addEdge("Bob", "Nicole");
                addEdge("Nicole", "Savannah");
                addEdge("Adam", "Nicole");
                addEdge("Nicole", "Violet");
                addEdge("Eleanor", "Nicole");
                addEdge("Nicole", "Nathan");
                addEdge("Nicole", "Aria");
                addEdge("Nicole", "Lincoln");
                addEdge("Nicole", "Hannah");
                addEdge("Nicole", "Carter");
                addEdge("Lily", "Nicole");
                addEdge("Charles", "Nicole");
                addEdge("Nora", "Nicole");
                addEdge("Joshua", "Nicole");
                addEdge("Zoey", "Nicole");
                addEdge("Andrew", "Nicole");
                addEdge("Riley", "Nicole");
                addEdge("Christopher", "Nicole");
                addEdge("Nicole", "Lorena");
                addEdge("Nicole", "Nahúm");
                addEdge("Nicole", "Gary");
                addEdge("Nicole", "Marlon");
                addEdge("Ryan", "Elizabeth");
                addEdge("Ryan", "Kevin");
                addEdge("Elizabeth", "Kevin");
                addEdge("Gary", "Rob");
                addEdge("Gary", "Emily");
                addEdge("Gary", "David");
                addEdge("Gary", "Sarah");
                addEdge("Gary", "Michael");
                addEdge("Gary", "Laura");
                addEdge("Gary", "Daniel");
                addEdge("Gary", "Jennifer");
                addEdge("Gary", "Ryan");
                addEdge("Gary", "Elizabeth");
                addEdge("Gary", "Savannah");
                addEdge("Gary", "Adam");
                addEdge("Gary", "Violet");
                addEdge("Gary", "Eleanor");
                addEdge("Gary", "Nathan");
                addEdge("Gary", "Alice");
                addEdge("Gary", "Mark");
                addEdge("Gary", "Nicole");
                addEdge("Gary", "Matthew");
                addEdge("Gary", "Lorena");
                addEdge("Gary", "Nahúm");
                addEdge("Gary", "Marlon");
                addEdge("Rob", "Ryan");
                addEdge("Rob", "Elizabeth");
                addEdge("Rob", "Kevin");
                addEdge("Nicole", "Rob");
                addEdge("Rob", "Matthew");
                addEdge("Rob", "Jessica");
                addEdge("Kevin", "Rob");
                addEdge("Mark", "Rob");
                addEdge("Alice", "Rob");
                addEdge("Savannah", "Rob");
                addEdge("Adam", "Rob");
                addEdge("Violet", "Rob");
                addEdge("Eleanor", "Rob");
                addEdge("Rob", "Nathan");
                addEdge("Rob", "Emily");
                addEdge("Rob", "David");
                addEdge("Rob", "Sarah");
                addEdge("Rob", "Michael");
                addEdge("Rob", "Laura");
                addEdge("Rob", "Daniel");
                addEdge("Rob", "Jennifer");
                addEdge("Rob", "Chris");
                addEdge("Rob", "Aria");
                addEdge("Rob", "Lincoln");
                addEdge("Rob", "Hannah");
                addEdge("Rob", "Carter");
                addEdge("Rob", "Lily");
                addEdge("Rob", "Charles");
                addEdge("Rob", "Nora");
                addEdge("Rob", "Joshua");
                addEdge("Rob", "Lorena");
                addEdge("Rob", "Nahúm");
                addEdge("Rob", "Gary");
                addEdge("Rob", "Marlon");
                addEdge("Maria", "Emily");
                addEdge("Maria", "David");
                addEdge("Maria", "Sarah");
                addEdge("Maria", "Michael");
                addEdge("Maria", "Laura");
                addEdge("Maria", "Daniel");
                addEdge("Maria", "Jennifer");
                addEdge("Maria", "Chris");
                addEdge("Maria", "Ryan");
                addEdge("Maria", "Elizabeth");
                addEdge("Maria", "Kevin");
                addEdge("Rob", "Maria");
                addEdge("Gary", "Maria");
                addEdge("Maria", "Nicole");
                addEdge("Maria", "Matthew");
                addEdge("Maria", "Jessica");
                addEdge("Alice", "Maria");
                addEdge("Bob", "Maria");
                addEdge("Ryan", "Maria");
                addEdge("Savannah", "Maria");
                addEdge("Adam", "Maria");
                addEdge("Maria", "Violet");
                addEdge("Maria", "Eleanor");
                addEdge("Maria", "Nathan");
                addEdge("Maria", "Aria");
                addEdge("Maria", "Lincoln");
                addEdge("Maria", "Hannah");
                addEdge("Maria", "Carter");
                addEdge("Maria", "Lily");
                addEdge("Maria", "Charles");
                addEdge("Maria", "Nora");
                addEdge("Maria", "Joshua");
                addEdge("Maria", "Zoey");
                addEdge("Maria", "Andrew");
                addEdge("Maria", "Anthony");
                addEdge("Maria", "Lorena");
                addEdge("Maria", "Nahúm");
                addEdge("Maria", "Gary");
                addEdge("Maria", "Marlon");
                addEdge("John", "David");
                addEdge("John", "Sarah");
                addEdge("John", "Michael");
                addEdge("John", "Laura");
                addEdge("John", "Daniel");
                addEdge("John", "Jennifer");
                addEdge("John", "Chris");
                addEdge("John", "Ryan");
                addEdge("John", "Elizabeth");
                addEdge("John", "Kevin");
                addEdge("John", "Emily");
                addEdge("Maria", "John");
                addEdge("Nicole", "John");
                addEdge("Matthew", "John");
                addEdge("John", "Jessica");
                addEdge("Kevin", "John");
                addEdge("Mark", "John");
                addEdge("Alice", "John");
                addEdge("John", "Lorena");
                addEdge("John", "Nahúm");
                addEdge("John", "Gary");
                addEdge("John", "Marlon");
                addEdge("Lorena", "David");
                addEdge("Lorena", "Sarah");
                addEdge("Lorena", "Michael");
                addEdge("Lorena", "Laura");
                addEdge("Lorena", "Daniel");
                addEdge("Lorena", "Jennifer");
                addEdge("Lorena", "Chris");
                addEdge("Lorena", "Ryan");
                addEdge("Lorena", "Elizabeth");
                addEdge("Lorena", "Kevin");
                addEdge("Lorena", "Nahúm");
                addEdge("Lorena", "Marlon");
                addEdge("Nahúm", "David");
                addEdge("Nahúm", "Sarah");
                addEdge("Nahúm", "Michael");
                addEdge("Nahúm", "Laura");
                addEdge("Nahúm", "Daniel");
                addEdge("Nahúm", "Jennifer");
                addEdge("Nahúm", "Chris");
                addEdge("Nahúm", "Ryan");
                addEdge("Nahúm", "Elizabeth");
                addEdge("Nahúm", "Kevin");
                addEdge("Nahúm", "Marlon");
                addEdge("Marlon", "David");
                addEdge("Marlon", "Sarah");
                addEdge("Marlon", "Michael");
                addEdge("Marlon", "Laura");
                addEdge("Marlon", "Daniel");
                addEdge("Marlon", "Jennifer");
                addEdge("Marlon", "Chris");
                addEdge("Marlon", "Ryan");
                addEdge("Marlon", "Elizabeth");
                addEdge("Marlon", "Kevin");
                addEdge("Emily", "Lorena");
                addEdge("Emily", "Nahúm");
                addEdge("Emily", "Gary");
                addEdge("Emily", "Marlon");
                addEdge("David", "Savannah");
                addEdge("David", "Anthony");
                addEdge("David", "Andrew");
                addEdge("David", "Lily");
                addEdge("David", "Layla");
                addEdge("David", "Nathan");
                addEdge("David", "Hannah");
                addEdge("David", "Carter");
                addEdge("David", "Violet");
                addEdge("Sarah", "Hannah");
                addEdge("Sarah", "Andrew");
                addEdge("Sarah", "Lily");
                addEdge("Sarah", "Layla");
                addEdge("Sarah", "Anthony");
                addEdge("Sarah", "Carter");
                break;


            default:
                System.out.println("Opción no válida");
                break;
        }

    }

    /**
     * Check if there is an edge between two vertices.
     *
     * @param label1 the first vertex name.
     * @param label2 the second vertex name.
     *
     * @return true if there is an edge between the two vertices, false otherwise.
     */
    public boolean hasEdge(String label1, String label2) {
        Vertex v1 = vertices.get(label1);
        Vertex v2 = vertices.get(label2);
        return v1 != null && v2 != null && v1.isAdjacent(v2);
    }

    /**
     * Get the graph vertices.
     *
     * @return the graph vertices.
     */
    public Map<String, Vertex> getVertices() {
        return vertices;
    }
}