import java.sql.SQLOutput;
import java.util.*;

/**
 * A class to represent a graph
 */
public class Graph {
    private Map<String, Vertex> vertices;

    /**
     * Create a new graph.
     */
    public Graph() {
        vertices = new HashMap<>();
    }

    /**
     * Add a new vertex to the graph.
     *
     * @param label the new vertex name.
     */
    void addVertex(String label) {
        vertices.putIfAbsent(label, new Vertex(label));
    }

    /**
     * Remove a vertex from the graph.
     *
     * @param label the vertex name to remove.
     */
    void removeVertex(String label) {
        Vertex v = vertices.remove(label);
        if (v != null) {
            vertices.values().forEach(adjacentVertices -> adjacentVertices.remove(v));
        }
    }

    /**
     * Add an edge to the graph.
     *
     * @param label1 the first vertex name.
     * @param label2 the second vertex name.
     */
    void addEdge(String label1, String label2) {
        Vertex v1 = vertices.get(label1);
        Vertex v2 = vertices.get(label2);
        if (v1 != null && v2 != null) {
            v1.addAdjacentVertex(v2);
            v2.addAdjacentVertex(v1);
        }
    }

    /**
     * Remove an edge from the graph.
     *
     * @param label1 the first vertex name.
     * @param label2 the second vertex name.
     */
    void removeEdge(String label1, String label2) {
        Vertex v1 = vertices.get(label1);
        Vertex v2 = vertices.get(label2);
        if (v1 != null && v2 != null) {
            v1.removeAdjacentVertex(v2);
            v2.removeAdjacentVertex(v1);
        }
    }

    /**
     * Initialize the graph with some example vertices and edges.
     */
    void createGraph(int option) {


        switch (option) {
            case 1:
                // Código para la primera versión del grafo
                //____________________________5 Vertices y 6 Arcos_________________________________
                addVertex("Bob");
                addVertex("Alice");
                addVertex("Mark");
                addVertex("Rob");
                addVertex("Maria");
                addEdge("Bob", "Alice");
                addEdge("Bob", "Rob");
                addEdge("Alice", "Mark");
                addEdge("Rob", "Mark");
                addEdge("Alice", "Maria");
                addEdge("Rob", "Maria");
                break;
            case 2:
                // Código para la segunda versión del grafo
                //____________________________________10 Vertices y 12 Arcos__________________________________
                addVertex("Bob");
                addVertex("Alice");
                addVertex("Mark");
                addVertex("Rob");
                addVertex("Maria");
                addVertex("John");
                addVertex("Emily");
                addVertex("David");
                addVertex("Sarah");
                addVertex("Michael");
                addEdge("Bob", "Alice");
                addEdge("Bob", "Rob");
                addEdge("Alice", "Rob");
                addEdge("Rob", "Maria");
                addEdge("Alice", "Maria");
                addEdge("Bob", "Maria");
                addEdge("Mark", "John");
                addEdge("John", "Emily");
                addEdge("Mark", "David");
                addEdge("David", "Sarah");
                addEdge("María", "Bob");
                addEdge("Sarah", "Michael");
                break;
            case 3:
                // Código para la tercera versión del grafo
                //_______________________________20 Vertices y 20 Arcos_________________________________
                addVertex("Bob");
                addVertex("Alice");
                addVertex("Mark");
                addVertex("Rob");
                addVertex("Maria");
                addVertex("John");
                addVertex("Emily");
                addVertex("David");
                addVertex("Sarah");
                addVertex("Michael");
                addVertex("Laura");
                addVertex("Daniel");
                addVertex("Jennifer");
                addVertex("Chris");
                addVertex("Jessica");
                addVertex("Matthew");
                addVertex("Nicole");
                addVertex("Ryan");
                addVertex("Elizabeth");
                addVertex("Kevin");
                addEdge("Bob", "Alice");
                addEdge("Bob", "Rob");
                addEdge("Alice", "Rob");
                addEdge("Rob", "Maria");
                addEdge("Alice", "Maria");
                addEdge("Bob", "Maria");
                addEdge("Bob", "John");
                addEdge("John", "Alice");
                addEdge("John", "Rob");
                addEdge("David", "Sarah");
                addEdge("John", "Maria");
                addEdge("Sarah", "Michael");
                addEdge("Laura", "Daniel");
                addEdge("Daniel", "Jennifer");
                addEdge("Laura", "Chris");
                addEdge("Chris", "Jessica");
                addEdge("Jessica", "Matthew");
                addEdge("Matthew", "Nicole");
                addEdge("Nicole", "Ryan");
                addEdge("Ryan", "Elizabeth");
                addEdge("Elizabeth", "Kevin");
                break;
            case 4:
                addVertex("Bob");
                addVertex("Alice");
                addVertex("Mark");
                addVertex("Rob");
                addVertex("Maria");
                addVertex("John");
                addVertex("Emily");
                addVertex("David");
                addVertex("Sarah");
                addVertex("Michael");
                addVertex("Laura");
                addVertex("Daniel");
                addVertex("Jennifer");
                addVertex("Chris");
                addVertex("Jessica");
                addVertex("Matthew");
                addVertex("Nicole");
                addVertex("Ryan");
                addVertex("Elizabeth");
                addVertex("Kevin");

                addEdge("Bob", "Alice");
                addEdge("Bob", "Rob");
                addEdge("Bob", "Maria");
                addEdge("Alice", "Rob");
                addEdge("Alice", "Maria");
                addEdge("Mark", "John");
                addEdge("Mark", "David");
                addEdge("Mark", "Daniel");
                addEdge("Rob", "Maria");
                addEdge("Rob", "John");
                addEdge("John", "Emily");
                addEdge("John", "Sarah");
                addEdge("John", "Michael");
                addEdge("Emily", "David");
                addEdge("Emily", "Laura");
                addEdge("Emily", "Chris");
                addEdge("David", "Sarah");
                addEdge("David", "Michael");
                addEdge("Sarah", "Laura");
                addEdge("Sarah", "Daniel");
                addEdge("Sarah", "Chris");
                addEdge("Michael", "Laura");
                addEdge("Michael", "Daniel");
                addEdge("Laura", "Daniel");
                addEdge("Laura", "Chris");
                addEdge("Laura", "Jessica");
                addEdge("Daniel", "Chris");
                addEdge("Daniel", "Jessica");
                addEdge("Chris", "Jessica");
                addEdge("Jessica", "Matthew");

                break;
            case 5:
                addVertex("Bob");
                addVertex("Alice");
                addVertex("Mark");
                addVertex("Rob");
                addVertex("Maria");
                addVertex("John");
                addVertex("Emily");
                addVertex("David");
                addVertex("Sarah");
                addVertex("Michael");
                addVertex("Laura");
                addVertex("Daniel");
                addVertex("Jennifer");
                addVertex("Chris");
                addVertex("Jessica");
                addVertex("Matthew");
                addVertex("Nicole");
                addVertex("Ryan");
                addVertex("Elizabeth");
                addVertex("Kevin");

                addEdge("Bob", "Alice");
                addEdge("Bob", "Mark");
                addEdge("Bob", "Rob");
                addEdge("Bob", "Maria");
                addEdge("Bob", "John");
                addEdge("Bob", "Emily");
                addEdge("Bob", "David");
                addEdge("Bob", "Sarah");
                addEdge("Bob", "Michael");
                addEdge("Bob", "Laura");
                addEdge("Bob", "Daniel");
                addEdge("Bob", "Jennifer");
                addEdge("Bob", "Chris");
                addEdge("Bob", "Jessica");
                addEdge("Bob", "Matthew");
                addEdge("Bob", "Nicole");
                addEdge("Bob", "Ryan");
                addEdge("Bob", "Elizabeth");
                addEdge("Bob", "Kevin");
                addEdge("Alice", "Mark");
                addEdge("Alice", "Rob");
                addEdge("Alice", "Maria");
                addEdge("Alice", "John");
                addEdge("Alice", "Emily");
                addEdge("Alice", "David");
                addEdge("Alice", "Sarah");
                addEdge("Alice", "Michael");
                addEdge("Alice", "Laura");
                addEdge("Alice", "Daniel");
                addEdge("Alice", "Jennifer");
                addEdge("Alice", "Chris");
                addEdge("Alice", "Jessica");
                addEdge("Alice", "Matthew");
                addEdge("Alice", "Nicole");
                addEdge("Alice", "Ryan");
                addEdge("Alice", "Elizabeth");
                addEdge("Alice", "Kevin");

                break;
            case 6:
                addVertex("Bob");
                addVertex("Alice");
                addVertex("Mark");
                addVertex("Rob");
                addVertex("Maria");
                addVertex("John");
                addVertex("Emily");
                addVertex("David");
                addVertex("Sarah");
                addVertex("Michael");
                addVertex("Laura");
                addVertex("Daniel");
                addVertex("Jennifer");
                addVertex("Chris");
                addVertex("Jessica");
                addVertex("Matthew");
                addVertex("Nicole");
                addVertex("Ryan");
                addVertex("Elizabeth");
                addVertex("Kevin");

                addEdge("Bob", "Alice");
                addEdge("Bob", "Mark");
                addEdge("Bob", "Rob");
                addEdge("Bob", "Maria");
                addEdge("Bob", "John");
                addEdge("Bob", "Emily");
                addEdge("Bob", "David");
                addEdge("Bob", "Sarah");
                addEdge("Bob", "Michael");
                addEdge("Bob", "Laura");
                addEdge("Bob", "Daniel");
                addEdge("Bob", "Jennifer");
                addEdge("Bob", "Chris");
                addEdge("Bob", "Jessica");
                addEdge("Bob", "Matthew");
                addEdge("Bob", "Nicole");
                addEdge("Bob", "Ryan");
                addEdge("Bob", "Elizabeth");
                addEdge("Bob", "Kevin");
                addEdge("Alice", "Mark");
                addEdge("Alice", "Rob");
                addEdge("Alice", "Maria");
                addEdge("Alice", "John");
                addEdge("Alice", "Emily");
                addEdge("Alice", "David");
                addEdge("Alice", "Sarah");
                addEdge("Alice", "Michael");
                addEdge("Alice", "Laura");
                addEdge("Alice", "Daniel");
                addEdge("Alice", "Jennifer");
                addEdge("Alice", "Chris");
                addEdge("Alice", "Jessica");
                addEdge("Alice", "Matthew");
                addEdge("Alice", "Nicole");
                addEdge("Alice", "Ryan");
                addEdge("Alice", "Elizabeth");
                addEdge("Alice", "Kevin");
                addEdge("Mark", "Rob");
                addEdge("Mark", "Maria");
                addEdge("Mark", "John");
                addEdge("Mark", "Emily");
                addEdge("Mark", "David");
                addEdge("Mark", "Sarah");
                addEdge("Mark", "Michael");
                addEdge("Mark", "Laura");
                addEdge("Mark", "Daniel");
                addEdge("Mark", "Jennifer");
                addEdge("Mark", "Chris");
                addEdge("Mark", "Jessica");
                addEdge("Mark", "Matthew");


                break;
            case 7:
                addVertex("Bob");
                addVertex("Alice");
                addVertex("Mark");
                addVertex("Rob");
                addVertex("Maria");
                addVertex("John");
                addVertex("Emily");
                addVertex("David");
                addVertex("Sarah");
                addVertex("Michael");
                addVertex("Laura");
                addVertex("Daniel");
                addVertex("Jennifer");
                addVertex("Chris");
                addVertex("Jessica");
                addVertex("Matthew");
                addVertex("Nicole");
                addVertex("Ryan");
                addVertex("Elizabeth");
                addVertex("Kevin");

                addEdge("Bob", "Alice");
                addEdge("Bob", "Mark");
                addEdge("Bob", "Rob");
                addEdge("Bob", "Maria");
                addEdge("Bob", "John");
                addEdge("Bob", "Emily");
                addEdge("Bob", "David");
                addEdge("Bob", "Sarah");
                addEdge("Bob", "Michael");
                addEdge("Bob", "Laura");
                addEdge("Bob", "Daniel");
                addEdge("Bob", "Jennifer");
                addEdge("Bob", "Chris");
                addEdge("Bob", "Jessica");
                addEdge("Bob", "Matthew");
                addEdge("Bob", "Nicole");
                addEdge("Bob", "Ryan");
                addEdge("Bob", "Elizabeth");
                addEdge("Bob", "Kevin");
                addEdge("Alice", "Mark");
                addEdge("Alice", "Rob");
                addEdge("Alice", "Maria");
                addEdge("Alice", "John");
                addEdge("Alice", "Emily");
                addEdge("Alice", "David");
                addEdge("Alice", "Sarah");
                addEdge("Alice", "Michael");
                addEdge("Alice", "Laura");
                addEdge("Alice", "Daniel");
                addEdge("Alice", "Jennifer");
                addEdge("Alice", "Chris");
                addEdge("Alice", "Jessica");
                addEdge("Alice", "Matthew");
                addEdge("Alice", "Nicole");
                addEdge("Alice", "Ryan");
                addEdge("Alice", "Elizabeth");
                addEdge("Alice", "Kevin");
                addEdge("Mark", "Rob");
                addEdge("Mark", "Maria");
                addEdge("Mark", "John");
                addEdge("Mark", "Emily");
                addEdge("Mark", "David");
                addEdge("Mark", "Sarah");
                addEdge("Mark", "Michael");
                addEdge("Mark", "Laura");
                addEdge("Mark", "Daniel");
                addEdge("Mark", "Jennifer");
                addEdge("Mark", "Chris");
                addEdge("Mark", "Jessica");
                addEdge("Mark", "Matthew");
                addEdge("Mark", "Nicole");
                addEdge("Mark", "Ryan");
                addEdge("Mark", "Elizabeth");
                addEdge("Mark", "Kevin");
                addEdge("Rob", "Maria");
                addEdge("Rob", "John");
                addEdge("Rob", "Emily");
                addEdge("Rob", "David");
                addEdge("Rob", "Sarah");
                addEdge("Rob", "Michael");
                addEdge("Rob", "Laura");
                addEdge("Rob", "Daniel");
                addEdge("Rob", "Jennifer");
                addEdge("Rob", "Chris");
                addEdge("Rob", "Jessica");
                addEdge("Rob", "Matthew");
                addEdge("Rob", "Nicole");
                addEdge("Rob", "Ryan");
                addEdge("Rob", "Elizabeth");
                addEdge("Rob", "Kevin");
                addEdge("Maria", "John");
                addEdge("Maria", "Emily");
                addEdge("Maria", "David");
                addEdge("Maria", "Sarah");
                addEdge("Maria", "Michael");
                addEdge("Maria", "Laura");
                addEdge("Maria", "Daniel");
                addEdge("Maria", "Jennifer");
                addEdge("Maria", "Chris");
                addEdge("Maria", "Jessica");

                break;
            case 8:
                addVertex("Bob");
                addVertex("Alice");
                addVertex("Mark");
                addVertex("Rob");
                addVertex("Maria");
                addVertex("John");
                addVertex("Emily");
                addVertex("David");
                addVertex("Sarah");
                addVertex("Michael");
                addVertex("Laura");
                addVertex("Daniel");
                addVertex("Jennifer");
                addVertex("Chris");
                addVertex("Jessica");
                addVertex("Matthew");
                addVertex("Nicole");
                addVertex("Ryan");
                addVertex("Elizabeth");
                addVertex("Kevin");
                addVertex("Sophia");
                addVertex("Jacob");
                addVertex("Olivia");
                addVertex("Emma");
                addVertex("Michael");
                addVertex("Ethan");
                addVertex("Ava");
                addVertex("Mia");
                addVertex("Alexander");
                addVertex("William");
                addVertex("James");
                addVertex("Elijah");
                addVertex("Benjamin");
                addVertex("Lucas");
                addVertex("Henry");
                addVertex("Charlotte");
                addVertex("Amelia");
                addVertex("Harper");
                addVertex("Evelyn");
                addVertex("Carmen");

                addEdge("Bob", "Alice");
                addEdge("Bob", "Mark");
                addEdge("Bob", "Rob");
                addEdge("Bob", "Maria");
                addEdge("Bob", "John");
                addEdge("Bob", "Emily");
                addEdge("Bob", "David");
                addEdge("Bob", "Sarah");
                addEdge("Bob", "Michael");
                addEdge("Bob", "Laura");
                addEdge("Bob", "Daniel");
                addEdge("Bob", "Jennifer");
                addEdge("Bob", "Chris");
                addEdge("Bob", "Jessica");
                addEdge("Bob", "Matthew");
                addEdge("Bob", "Nicole");
                addEdge("Bob", "Ryan");
                addEdge("Bob", "Elizabeth");
                addEdge("Bob", "Kevin");
                addEdge("Bob", "Sophia");
                addEdge("Bob", "Jacob");
                addEdge("Bob", "Olivia");
                addEdge("Bob", "Emma");
                addEdge("Bob", "Michael");
                addEdge("Bob", "Ethan");
                addEdge("Bob", "Ava");
                addEdge("Bob", "Mia");
                addEdge("Bob", "Alexander");
                addEdge("Bob", "William");
                addEdge("Bob", "James");
                addEdge("Bob", "Elijah");
                addEdge("Bob", "Benjamin");
                addEdge("Bob", "Lucas");
                addEdge("Bob", "Henry");
                addEdge("Bob", "Charlotte");
                addEdge("Bob", "Amelia");
                addEdge("Bob", "Harper");
                addEdge("Alice", "Mark");
                addEdge("Alice", "Rob");
                addEdge("Alice", "Maria");
                addEdge("Alice", "John");
                addEdge("Alice", "Emily");
                addEdge("Alice", "David");
                addEdge("Alice", "Sarah");
                addEdge("Alice", "Michael");
                addEdge("Alice", "Laura");
                addEdge("Alice", "Daniel");
                addEdge("Alice", "Jennifer");
                addEdge("Alice", "Chris");
                addEdge("Alice", "Jessica");
                addEdge("Alice", "Matthew");
                addEdge("Alice", "Nicole");
                addEdge("Alice", "Ryan");
                addEdge("Alice", "Elizabeth");
                addEdge("Alice", "Kevin");
                addEdge("Alice", "Sophia");
                addEdge("Alice", "Jacob");
                addEdge("Alice", "Olivia");
                addEdge("Alice", "Emma");
                addEdge("Alice", "Michael");
                addEdge("Alice", "Ethan");
                addEdge("Alice", "Ava");
                addEdge("Alice", "Mia");
                addEdge("Alice", "Alexander");
                addEdge("Alice", "William");
                addEdge("Alice", "James");
                addEdge("Alice", "Elijah");
                addEdge("Alice", "Benjamin");
                addEdge("Alice", "Lucas");
                addEdge("Alice", "Henry");
                addEdge("Alice", "Charlotte");
                addEdge("Alice", "Amelia");
                addEdge("Alice", "Harper");
                addEdge("Mark", "Rob");
                addEdge("Mark", "Maria");
                addEdge("Mark", "John");
                addEdge("Mark", "Emily");
                addEdge("Mark", "David");
                addEdge("Mark", "Sarah");
                addEdge("Mark", "Michael");
                addEdge("Mark", "Laura");
                addEdge("Mark", "Daniel");
                addEdge("Mark", "Jennifer");
                addEdge("Mark", "Chris");
                addEdge("Mark", "Jessica");
                addEdge("Mark", "Matthew");
                addEdge("Mark", "Nicole");
                addEdge("Mark", "Ryan");
                addEdge("Mark", "Elizabeth");
                addEdge("Mark", "Kevin");
                addEdge("Mark", "Sophia");
                addEdge("Mark", "Jacob");
                addEdge("Mark", "Olivia");
                addEdge("Mark", "Emma");
                addEdge("Mark", "Michael");
                addEdge("Mark", "Ethan");
                addEdge("Mark", "Ava");
                addEdge("Mark", "Mia");
                addEdge("Mark", "Alexander");
                addEdge("Mark", "William");
                addEdge("Mark", "James");
                addEdge("Mark", "Elijah");
                addEdge("Mark", "Benjamin");
                addEdge("Mark", "Lucas");
                addEdge("Mark", "Henry");
                addEdge("Mark", "Charlotte");
                addEdge("Mark", "Amelia");
                addEdge("Mark", "Harper");
                addEdge("Maria", "John");
                addEdge("Maria", "Emily");
                addEdge("Maria", "David");
                addEdge("Maria", "Sarah");
                addEdge("Maria", "Michael");
                addEdge("Maria", "Laura");
                addEdge("Maria", "Daniel");
                addEdge("Maria", "Jennifer");
                addEdge("Maria", "Chris");
                addEdge("Maria", "Jessica");
                addEdge("Maria", "Matthew");
                addEdge("Maria", "Nicole");
                break;
            case 9:
                addVertex("Oliver");
                addVertex("Liam");
                addVertex("Lucas");
                addVertex("Emma");
                addVertex("Charlotte");
                addVertex("Sophia");
                addVertex("Amelia");
                addVertex("Isabella");
                addVertex("Mia");
                addVertex("Evelyn");
                addVertex("Aria");
                addVertex("Harper");
                addVertex("Ella");
                addVertex("Avery");
                addVertex("Luna");
                addVertex("Grace");
                addVertex("Chloe");
                addVertex("Layla");
                addVertex("Zoey");
                addVertex("Hazel");
                addVertex("Lily");
                addVertex("Ellie");
                addVertex("Violet");
                addVertex("Aurora");
                addVertex("Savannah");
                addVertex("Claire");
                addVertex("Stella");
                addVertex("Isla");
                addVertex("Emily");
                addVertex("Nora");
                addVertex("Maya");
                addVertex("Penelope");
                addVertex("Mila");
                addVertex("Lila");
                addVertex("Elizabeth");
                addVertex("Scarlett");
                addVertex("Charlie");
                addVertex("Aria");
                addVertex("Natalie");
                addVertex("Abigail");
                addVertex("Luna");
                addVertex("Eleanor");
                addVertex("Hannah");
                addVertex("Lucy");
                addVertex("Victoria");
                addVertex("Zoe");
                addVertex("Nora");
                addVertex("Riley");
                addVertex("Eliana");
                addVertex("Leah");
                addVertex("Hazel");
                addVertex("Violet");
                addVertex("Aria");
                addVertex("Hannah");
                addVertex("Madison");
                addVertex("Emilia");
                addVertex("Ella");
                addVertex("Zoey");
                addVertex("Orlando");
                addVertex("Anarey");

                addEdge("Oliver", "Liam");
                addEdge("Oliver", "Lucas");
                addEdge("Oliver", "Emma");
                addEdge("Oliver", "Charlotte");
                addEdge("Oliver", "Sophia");
                addEdge("Oliver", "Amelia");
                addEdge("Oliver", "Isabella");
                addEdge("Oliver", "Mia");
                addEdge("Oliver", "Evelyn");
                addEdge("Oliver", "Aria");
                addEdge("Oliver", "Harper");
                addEdge("Oliver", "Ella");
                addEdge("Oliver", "Avery");
                addEdge("Oliver", "Luna");
                addEdge("Oliver", "Grace");
                addEdge("Oliver", "Chloe");
                addEdge("Oliver", "Layla");
                addEdge("Oliver", "Zoey");
                addEdge("Oliver", "Hazel");
                addEdge("Oliver", "Lily");
                addEdge("Oliver", "Ellie");
                addEdge("Oliver", "Violet");
                addEdge("Oliver", "Aurora");
                addEdge("Oliver", "Savannah");
                addEdge("Oliver", "Claire");
                addEdge("Oliver", "Stella");
                addEdge("Oliver", "Isla");
                addEdge("Oliver", "Emily");
                addEdge("Oliver", "Nora");
                addEdge("Oliver", "Maya");
                addEdge("Oliver", "Penelope");
                addEdge("Oliver", "Mila");
                addEdge("Oliver", "Lila");
                addEdge("Oliver", "Elizabeth");
                addEdge("Oliver", "Scarlett");
                addEdge("Oliver", "Charlie");
                addEdge("Oliver", "Aria");
                addEdge("Oliver", "Natalie");
                addEdge("Oliver", "Abigail");
                addEdge("Oliver", "Luna");
                addEdge("Oliver", "Eleanor");
                addEdge("Oliver", "Hannah");
                addEdge("Oliver", "Lucy");
                addEdge("Oliver", "Victoria");
                addEdge("Oliver", "Zoe");
                addEdge("Oliver", "Nora");
                addEdge("Oliver", "Riley");
                addEdge("Oliver", "Eliana");
                addEdge("Oliver", "Leah");
                addEdge("Oliver", "Hazel");
                addEdge("Oliver", "Violet");
                addEdge("Oliver", "Aria");
                addEdge("Oliver", "Hannah");
                addEdge("Oliver", "Madison");
                addEdge("Oliver", "Emilia");
                addEdge("Oliver", "Ella");
                addEdge("Oliver", "Zoey");
                addEdge("Bob", "Liam");
                addEdge("Bob", "Lucas");
                addEdge("Bob", "Emma");
                addEdge("Bob", "Charlotte");
                addEdge("Bob", "Sophia");
                addEdge("Bob", "Amelia");
                addEdge("Bob", "Isabella");
                addEdge("Bob", "Mia");
                addEdge("Bob", "Evelyn");
                addEdge("Bob", "Aria");
                addEdge("Bob", "Harper");
                addEdge("Bob", "Ella");
                addEdge("Bob", "Avery");
                addEdge("Bob", "Luna");
                addEdge("Bob", "Grace");
                addEdge("Bob", "Chloe");
                addEdge("Bob", "Layla");
                addEdge("Bob", "Zoey");
                addEdge("Bob", "Hazel");
                addEdge("Bob", "Lily");
                addEdge("Bob", "Ellie");
                addEdge("Bob", "Violet");
                addEdge("Bob", "Aurora");
                addEdge("Bob", "Savannah");
                addEdge("Bob", "Claire");
                addEdge("Bob", "Stella");
                addEdge("Bob", "Isla");
                addEdge("Bob", "Emily");
                addEdge("Bob", "Nora");
                addEdge("Bob", "Maya");
                addEdge("Bob", "Penelope");
                addEdge("Bob", "Mila");
                addEdge("Bob", "Lila");
                addEdge("Bob", "Elizabeth");
                addEdge("Bob", "Scarlett");
                addEdge("Bob", "Charlie");
                addEdge("Bob", "Aria");
                addEdge("Bob", "Natalie");
                addEdge("Bob", "Abigail");
                addEdge("Bob", "Luna");
                addEdge("Bob", "Eleanor");
                addEdge("Bob", "Hannah");
                addEdge("Bob", "Lucy");
                addEdge("Bob", "Victoria");
                addEdge("Bob", "Zoe");
                addEdge("Bob", "Nora");
                addEdge("Bob", "Riley");
                addEdge("Bob", "Eliana");
                addEdge("Bob", "Leah");
                addEdge("Bob", "Hazel");
                addEdge("Bob", "Violet");
                addEdge("Bob", "Aria");
                addEdge("Bob", "Hannah");
                addEdge("Bob", "Madison");
                addEdge("Bob", "Emilia");
                addEdge("Bob", "Ella");
                addEdge("Bob", "Zoey");
                addEdge("Alice", "Liam");
                addEdge("Alice", "Lucas");
                addEdge("Alice", "Emma");
                addEdge("Alice", "Charlotte");
                addEdge("Alice", "Sophia");
                addEdge("Alice", "Amelia");
                addEdge("Alice", "Isabella");
                addEdge("Alice", "Mia");
                addEdge("Alice", "Evelyn");
                addEdge("Alice", "Aria");
                addEdge("Alice", "Harper");
                addEdge("Alice", "Ella");
                addEdge("Alice", "Avery");
                addEdge("Alice", "Luna");
                addEdge("Alice", "Grace");
                addEdge("Alice", "Chloe");
                addEdge("Alice", "Layla");
                addEdge("Alice", "Zoey");
                addEdge("Alice", "Hazel");
                addEdge("Alice", "Lily");
                addEdge("Alice", "Ellie");
                addEdge("Alice", "Violet");
                addEdge("Alice", "Aurora");
                addEdge("Alice", "Savannah");
                addEdge("Alice", "Claire");
                addEdge("Alice", "Stella");
                addEdge("Alice", "Isla");
                addEdge("Alice", "Emily");
                addEdge("Alice", "Nora");
                addEdge("Alice", "Maya");
                addEdge("Alice", "Penelope");
                addEdge("Alice", "Mila");
                addEdge("Alice", "Lila");
                addEdge("Alice", "Elizabeth");
                addEdge("Alice", "Scarlett");
                addEdge("Alice", "Charlie");
                addEdge("Alice", "Aria");
                addEdge("Alice", "Natalie");
                addEdge("Alice", "Abigail");
                addEdge("Alice", "Luna");
                addEdge("Alice", "Eleanor");
                addEdge("Alice", "Hannah");
                addEdge("Alice", "Lucy");
                addEdge("Alice", "Victoria");
                addEdge("Alice", "Zoe");
                addEdge("Alice", "Nora");
                addEdge("Alice", "Riley");
                addEdge("Alice", "Eliana");
                addEdge("Alice", "Leah");
                addEdge("Alice", "Hazel");
                addEdge("Alice", "Violet");
                addEdge("Alice", "Aria");
                addEdge("Alice", "Hannah");
                addEdge("Alice", "Madison");
                addEdge("Alice", "Emilia");
                addEdge("Alice", "Ella");
                addEdge("Alice", "Zoey");
                addEdge("Mark", "Liam");
                addEdge("Mark", "Lucas");
                addEdge("Mark", "Emma");
                addEdge("Mark", "Charlotte");
                addEdge("Mark", "Sophia");
                addEdge("Mark", "Amelia");
                addEdge("Mark", "Isabella");
                addEdge("Mark", "Mia");
                addEdge("Mark", "Evelyn");
                addEdge("Mark", "Aria");
                addEdge("Mark", "Harper");
                addEdge("Mark", "Ella");
                addEdge("Mark", "Avery");
                addEdge("Mark", "Luna");
                addEdge("Mark", "Grace");
                addEdge("Mark", "Chloe");
                addEdge("Mark", "Layla");
                addEdge("Mark", "Zoey");
                addEdge("Mark", "Hazel");
                addEdge("Mark", "Lily");
                addEdge("Mark", "Ellie");
                addEdge("Mark", "Violet");
                addEdge("Mark", "Aurora");
                addEdge("Mark", "Savannah");
                addEdge("Mark", "Claire");
                addEdge("Mark", "Stella");
                addEdge("Mark", "Isla");
                addEdge("Mark", "Emily");
                addEdge("Mark", "Nora");
                addEdge("Mark", "Maya");
                addEdge("Mark", "Penelope");
                addEdge("Mark", "Mila");
                addEdge("Mark", "Lila");
                addEdge("Mark", "Elizabeth");
                addEdge("Mark", "Scarlett");
                addEdge("Mark", "Charlie");
                addEdge("Mark", "Aria");
                addEdge("Mark", "Natalie");
                addEdge("Mark", "Abigail");
                addEdge("Mark", "Luna");
                addEdge("Mark", "Eleanor");
                addEdge("Mark", "Hannah");
                addEdge("Mark", "Lucy");
                addEdge("Mark", "Victoria");
                addEdge("Mark", "Zoe");
                addEdge("Mark", "Nora");
                addEdge("Mark", "Riley");
                addEdge("Mark", "Eliana");
                addEdge("Mark", "Leah");
                addEdge("Mark", "Hazel");
                addEdge("Mark", "Violet");
                addEdge("Mark", "Aria");
                addEdge("Mark", "Hannah");
                addEdge("Mark", "Madison");
                addEdge("Mark", "Emilia");
                addEdge("Mark", "Ella");
                addEdge("Mark", "Zoey");
                addEdge("Rob", "Liam");
                addEdge("Rob", "Lucas");
                addEdge("Rob", "Emma");
                addEdge("Rob", "Charlotte");
                addEdge("Rob", "Sophia");
                addEdge("Rob", "Amelia");
                addEdge("Rob", "Isabella");
                addEdge("Rob", "Mia");
                addEdge("Rob", "Evelyn");
                addEdge("Rob", "Aria");
                addEdge("Rob", "Harper");
                addEdge("David", "Zoey");

                break;
            case 10:
                addVertex("Bob");
                addVertex("Alice");
                addVertex("Mark");
                addVertex("Rob");
                addVertex("Maria");
                addVertex("John");
                addVertex("Emily");
                addVertex("David");
                addVertex("Sarah");
                addVertex("Michael");
                addVertex("Laura");
                addVertex("Daniel");
                addVertex("Jennifer");
                addVertex("Chris");
                addVertex("Jessica");
                addVertex("Matthew");
                addVertex("Nicole");
                addVertex("Ryan");
                addVertex("Elizabeth");
                addVertex("Kevin");
                addVertex("Alex");
                addVertex("Sophia");
                addVertex("William");
                addVertex("Isabella");
                addVertex("Ethan");
                addVertex("Ava");
                addVertex("James");
                addVertex("Olivia");
                addVertex("Benjamin");
                addVertex("Amelia");
                addVertex("Lucas");
                addVertex("Mia");
                addVertex("Henry");
                addVertex("Charlotte");
                addVertex("Alexander");
                addVertex("Elijah");
                addVertex("Harper");
                addVertex("Michael");
                addVertex("Evelyn");
                addVertex("Daniel");
                addVertex("Abigail");
                addVertex("Jackson");
                addVertex("Emily");
                addVertex("Sebastian");
                addVertex("Elizabeth");
                addVertex("Aiden");
                addVertex("Avery");
                addVertex("Matthew");
                addVertex("Sofia");
                addVertex("Samuel");
                addVertex("Camila");
                addVertex("David");
                addVertex("Ella");
                addVertex("Joseph");
                addVertex("Madison");
                addVertex("Gabriel");
                addVertex("Scarlett");
                addVertex("Dylan");
                addVertex("Grace");
                addVertex("Luke");
                addVertex("Chloe");
                addVertex("Anthony");
                addVertex("Penelope");
                addVertex("Isaac");
                addVertex("Layla");
                addVertex("Christopher");
                addVertex("Riley");
                addVertex("Andrew");
                addVertex("Zoey");
                addVertex("Joshua");
                addVertex("Nora");
                addVertex("Charles");
                addVertex("Lily");
                addVertex("Carter");
                addVertex("Hannah");
                addVertex("Lincoln");
                addVertex("Aria");
                addVertex("Nathan");
                addVertex("Eleanor");
                addVertex("Ryan");
                addVertex("Violet");
                addVertex("Adam");
                addVertex("Savannah");

                addEdge("Bob", "Alice");
                addEdge("Bob", "Mark");
                addEdge("Bob", "Rob");
                addEdge("Bob", "Maria");
                addEdge("Bob", "John");
                addEdge("Bob", "Emily");
                addEdge("Bob", "David");
                addEdge("Bob", "Sarah");
                addEdge("Bob", "Michael");
                addEdge("Bob", "Laura");
                addEdge("Bob", "Daniel");
                addEdge("Bob", "Jennifer");
                addEdge("Bob", "Chris");
                addEdge("Bob", "Jessica");
                addEdge("Bob", "Matthew");
                addEdge("Bob", "Nicole");
                addEdge("Bob", "Ryan");
                addEdge("Bob", "Elizabeth");
                addEdge("Bob", "Kevin");
                addEdge("Alice", "Mark");
                addEdge("Alice", "Rob");
                addEdge("Alice", "Maria");
                addEdge("Alice", "John");
                addEdge("Alice", "Emily");
                addEdge("Alice", "David");
                addEdge("Alice", "Sarah");
                addEdge("Alice", "Michael");
                addEdge("Alice", "Laura");
                addEdge("Alice", "Daniel");
                addEdge("Alice", "Jennifer");
                addEdge("Alice", "Chris");
                addEdge("Alice", "Jessica");
                addEdge("Alice", "Matthew");
                addEdge("Alice", "Nicole");
                addEdge("Alice", "Ryan");
                addEdge("Alice", "Elizabeth");
                addEdge("Alice", "Kevin");
                addEdge("Mark", "Rob");
                addEdge("Mark", "Maria");
                addEdge("Mark", "John");
                addEdge("Mark", "Emily");
                addEdge("Mark", "David");
                addEdge("Mark", "Sarah");
                addEdge("Mark", "Michael");
                addEdge("Mark", "Laura");
                addEdge("Mark", "Daniel");
                addEdge("Mark", "Jennifer");
                addEdge("Mark", "Chris");
                addEdge("Mark", "Jessica");
                addEdge("Mark", "Matthew");
                addEdge("Mark", "Nicole");
                addEdge("Mark", "Ryan");
                addEdge("Mark", "Elizabeth");
                addEdge("Mark", "Kevin");


                addEdge("Chris", "Kevin");
                addEdge("Jessica", "Matthew");
                addEdge("Jessica", "Nicole");
                addEdge("Jessica", "Ryan");
                addEdge("Jessica", "Elizabeth");
                addEdge("Jessica", "Kevin");
                addEdge("Matthew", "Nicole");
                addEdge("Matthew", "Ryan");
                addEdge("Matthew", "Elizabeth");
                addEdge("Matthew", "Kevin");
                addEdge("Nicole", "Ryan");
                addEdge("Nicole", "Elizabeth");
                addEdge("Nicole", "Kevin");
                addEdge("Ryan", "Elizabeth");
                addEdge("Ryan", "Kevin");
                addEdge("Elizabeth", "Kevin");
                addEdge("Kevin", "Mark");
                addEdge("Kevin", "Rob");
                addEdge("Kevin", "Maria");
                addEdge("Kevin", "John");
                addEdge("Kevin", "Emily");
                addEdge("Kevin", "David");
                addEdge("Kevin", "Sarah");
                addEdge("Kevin", "Michael");
                addEdge("Kevin", "Laura");
                addEdge("Kevin", "Daniel");
                addEdge("Kevin", "Jennifer");
                addEdge("Kevin", "Chris");
                addEdge("Kevin", "Jessica");
                addEdge("Kevin", "Matthew");
                addEdge("Kevin", "Nicole");
                addEdge("Kevin", "Ryan");
                addEdge("Kevin", "Elizabeth");
                addEdge("Mark", "Kevin");
                addEdge("Rob", "Kevin");
                addEdge("Maria", "Kevin");
                addEdge("John", "Kevin");
                addEdge("Emily", "Kevin");
                addEdge("David", "Kevin");
                addEdge("Sarah", "Kevin");
                addEdge("Michael", "Kevin");
                addEdge("Laura", "Kevin");
                addEdge("Daniel", "Kevin");
                addEdge("Jennifer", "Kevin");
                addEdge("Chris", "Kevin");
                addEdge("Jessica", "Kevin");
                addEdge("Matthew", "Kevin");
                addEdge("Nicole", "Kevin");
                addEdge("Ryan", "Kevin");
                addEdge("Elizabeth", "Kevin");
                addEdge("Kevin", "Bob");
                addEdge("Kevin", "Alice");
                addEdge("Kevin", "Mark");
                addEdge("Kevin", "Rob");
                addEdge("Kevin", "Maria");
                addEdge("Kevin", "John");
                addEdge("Kevin", "Emily");
                addEdge("Kevin", "David");
                addEdge("Kevin", "Sarah");
                addEdge("Kevin", "Michael");
                addEdge("Kevin", "Laura");
                addEdge("Kevin", "Daniel");
                addEdge("Kevin", "Jennifer");
                addEdge("Kevin", "Chris");
                addEdge("Kevin", "Jessica");
                addEdge("Kevin", "Matthew");
                addEdge("Kevin", "Nicole");
                addEdge("Kevin", "Ryan");
                addEdge("Kevin", "Elizabeth");
                addEdge("Mark", "Kevin");
                addEdge("Rob", "Kevin");
                addEdge("Maria", "Kevin");
                addEdge("John", "Kevin");
                addEdge("Emily", "Kevin");
                addEdge("David", "Kevin");
                addEdge("Sarah", "Kevin");
                addEdge("Michael", "Kevin");
                addEdge("Laura", "Kevin");
                addEdge("Daniel", "Kevin");
                addEdge("Jennifer", "Kevin");
                addEdge("Chris", "Kevin");
                addEdge("Jessica", "Kevin");
                addEdge("Matthew", "Kevin");
                addEdge("Nicole", "Kevin");
                addEdge("Ryan", "Kevin");
                addEdge("Elizabeth", "Kevin");
                addEdge("Kevin", "Bob");
                addEdge("Kevin", "Alice");
                addEdge("Kevin", "Mark");
                addEdge("Kevin", "Rob");
                addEdge("Kevin", "Maria");
                addEdge("Kevin", "John");
                addEdge("Kevin", "Emily");
                addEdge("Kevin", "David");
                addEdge("Kevin", "Sarah");
                addEdge("Kevin", "Michael");
                addEdge("Kevin", "Laura");
                addEdge("Kevin", "Daniel");
                addEdge("Kevin", "Jennifer");
                addEdge("Kevin", "Chris");
                addEdge("Kevin", "Jessica");
                addEdge("Kevin", "Matthew");
                addEdge("Kevin", "Nicole");
                addEdge("Kevin", "Ryan");
                addEdge("Kevin", "Elizabeth");
                addEdge("Mark", "Kevin");
                addEdge("Rob", "Kevin");
                addEdge("Maria", "Kevin");
                addEdge("John", "Kevin");
                addEdge("Emily", "Kevin");
                addEdge("David", "Kevin");
                addEdge("Sarah", "Kevin");
                addEdge("Michael", "Kevin");
                addEdge("Laura", "Kevin");
                addEdge("Daniel", "Kevin");
                addEdge("Jennifer", "Kevin");
                addEdge("Chris", "Kevin");
                addEdge("Jessica", "Kevin");
                addEdge("Matthew", "Kevin");
                addEdge("Nicole", "Kevin");
                addEdge("Ryan", "Kevin");
                addEdge("Elizabeth", "Kevin");
                addEdge("Kevin", "Bob");
                addEdge("Kevin", "Alice");
                addEdge("Kevin", "Mark");
                addEdge("Kevin", "Rob");
                addEdge("Kevin", "Maria");
                addEdge("Kevin", "John");
                addEdge("Kevin", "Emily");
                addEdge("Kevin", "David");
                addEdge("Kevin", "Sarah");
                addEdge("Kevin", "Michael");
                addEdge("Kevin", "Laura");
                addEdge("Kevin", "Daniel");
                addEdge("Kevin", "Jennifer");
                addEdge("Kevin", "Chris");
                addEdge("Kevin", "Jessica");
                addEdge("Kevin", "Matthew");
                addEdge("Kevin", "Nicole");
                addEdge("Kevin", "Ryan");
                addEdge("Kevin", "Elizabeth");
                addEdge("Chris", "Jessica");
                addEdge("Chris", "Matthew");
                addEdge("Chris", "Nicole");
                addEdge("Chris", "Ryan");
                addEdge("Chris", "Elizabeth");
                addEdge("Chris", "Kevin");
                addEdge("Jessica", "Matthew");
                addEdge("Jessica", "Nicole");
                addEdge("Jessica", "Ryan");
                addEdge("Jessica", "Elizabeth");
                addEdge("Jessica", "Kevin");
                addEdge("Matthew", "Nicole");
                addEdge("Matthew", "Ryan");
                addEdge("Matthew", "Elizabeth");
                addEdge("Matthew", "Kevin");
                addEdge("Nicole", "Ryan");
                addEdge("Nicole", "Elizabeth");
                addEdge("Nicole", "Kevin");
                addEdge("Ryan", "Elizabeth");
                addEdge("Ryan", "Kevin");
                addEdge("Elizabeth", "Kevin");
                addEdge("Kevin", "Mark");
                addEdge("Kevin", "Rob");
                addEdge("Kevin", "Maria");
                addEdge("Kevin", "John");
                addEdge("Kevin", "Emily");
                addEdge("Kevin", "David");
                addEdge("Kevin", "Sarah");
                addEdge("Kevin", "Michael");
                addEdge("Kevin", "Laura");
                addEdge("Kevin", "Daniel");
                addEdge("Kevin", "Jennifer");
                addEdge("Kevin", "Chris");
                addEdge("Kevin", "Jessica");
                addEdge("Kevin", "Matthew");
                addEdge("Kevin", "Nicole");
                addEdge("Kevin", "Ryan");
                addEdge("Kevin", "Elizabeth");
                addEdge("Mark", "Rob");
                addEdge("Mark", "Maria");
                addEdge("Mark", "John");
                addEdge("Mark", "Emily");
                addEdge("Mark", "David");
                addEdge("Mark", "Sarah");
                addEdge("Mark", "Michael");
                addEdge("Mark", "Laura");
                addEdge("Mark", "Daniel");
                addEdge("Mark", "Jennifer");
                addEdge("Mark", "Chris");
                addEdge("Mark", "Jessica");
                addEdge("Mark", "Matthew");
                addEdge("Mark", "Nicole");
                addEdge("Mark", "Ryan");
                addEdge("Mark", "Elizabeth");
                addEdge("Mark", "Kevin");
                addEdge("Rob", "Maria");
                addEdge("Rob", "John");
                addEdge("Rob", "Emily");
                addEdge("Rob", "David");
                addEdge("Rob", "Sarah");
                addEdge("Rob", "Michael");
                addEdge("Rob", "Laura");
                addEdge("Rob", "Daniel");
                addEdge("Rob", "Jennifer");
                addEdge("Rob", "Chris");
                addEdge("Rob", "Jessica");
                addEdge("Rob", "Matthew");
                addEdge("Rob", "Nicole");
                addEdge("Rob", "Ryan");
                addEdge("Rob", "Elizabeth");
                addEdge("Rob", "Kevin");
                addEdge("Maria", "John");
                addEdge("Maria", "Emily");
                addEdge("Maria", "David");
                addEdge("Maria", "Sarah");
                addEdge("Maria", "Michael");
                addEdge("Maria", "Laura");
                addEdge("Maria", "Daniel");
                addEdge("Maria", "Jennifer");
                addEdge("Maria", "Chris");
                addEdge("Maria", "Jessica");
                addEdge("Maria", "Matthew");
                addEdge("Maria", "Nicole");
                addEdge("Maria", "Ryan");
                addEdge("Maria", "Elizabeth");
                addEdge("Maria", "Kevin");
                addEdge("John", "Emily");
                addEdge("John", "David");
                addEdge("John", "Sarah");
                addEdge("John", "Michael");
                addEdge("John", "Laura");
                addEdge("John", "Daniel");
                addEdge("John", "Jennifer");
                addEdge("John", "Chris");
                addEdge("John", "Jessica");
                addEdge("John", "Matthew");
                addEdge("John", "Nicole");
                addEdge("John", "Ryan");
                addEdge("John", "Elizabeth");
                addEdge("John", "Kevin");
                addEdge("Emily", "David");
                addEdge("Emily", "Sarah");
                addEdge("Emily", "Michael");
                addEdge("Emily", "Laura");
                addEdge("Emily", "Daniel");
                addEdge("Emily", "Jennifer");
                addEdge("Emily", "Chris");
                addEdge("Emily", "Jessica");
                addEdge("Emily", "Matthew");
                addEdge("Emily", "Nicole");
                addEdge("Emily", "Ryan");
                addEdge("Emily", "Elizabeth");
                addEdge("Emily", "Kevin");
                addEdge("David", "Sarah");
                addEdge("David", "Michael");
                addEdge("David", "Laura");
                addEdge("David", "Daniel");
                addEdge("David", "Jennifer");
                addEdge("David", "Chris");
                addEdge("David", "Jessica");
                addEdge("David", "Matthew");
                addEdge("David", "Nicole");
                addEdge("David", "Ryan");
                addEdge("David", "Elizabeth");
                addEdge("David", "Kevin");
                addEdge("Sarah", "Michael");
                addEdge("Sarah", "Laura");
                addEdge("Sarah", "Daniel");
                addEdge("Sarah", "Jennifer");
                addEdge("Sarah", "Chris");
                addEdge("Sarah", "Jessica");
                addEdge("Sarah", "Matthew");
                addEdge("Sarah", "Nicole");
                addEdge("Sarah", "Ryan");
                addEdge("Sarah", "Elizabeth");
                addEdge("Sarah", "Kevin");
                addEdge("Michael", "Laura");
                addEdge("Michael", "Daniel");
                addEdge("Michael", "Jennifer");
                addEdge("Michael", "Chris");
                addEdge("Michael", "Jessica");
                addEdge("Michael", "Matthew");
                addEdge("Michael", "Nicole");
                addEdge("Michael", "Ryan");
                addEdge("Michael", "Elizabeth");
                addEdge("Michael", "Kevin");
                addEdge("Laura", "Daniel");
                addEdge("Laura", "Jennifer");
                addEdge("Laura", "Chris");
                addEdge("Laura", "Jessica");
                addEdge("Laura", "Matthew");
                addEdge("Laura", "Nicole");
                addEdge("Laura", "Ryan");
                addEdge("Laura", "Elizabeth");
                addEdge("Laura", "Kevin");
                addEdge("Daniel", "Jennifer");
                addEdge("Daniel", "Chris");
                addEdge("Daniel", "Jessica");
                addEdge("Daniel", "Matthew");
                addEdge("Daniel", "Nicole");
                addEdge("Daniel", "Ryan");
                addEdge("Daniel", "Elizabeth");
                addEdge("Daniel", "Kevin");
                addEdge("Jennifer", "Chris");
                addEdge("Jennifer", "Jessica");
                addEdge("Jennifer", "Matthew");
                addEdge("Jennifer", "Nicole");
                addEdge("Jennifer", "Ryan");
                addEdge("Jennifer", "Elizabeth");
                addEdge("Jennifer", "Kevin");
                addEdge("Chris", "Mark");
                addEdge("Chris", "Rob");
                addEdge("Chris", "Maria");
                addEdge("Chris", "John");
                addEdge("Chris", "Emily");
                addEdge("Chris", "David");
                addEdge("Chris", "Sarah");
                addEdge("Chris", "Michael");
                addEdge("Chris", "Laura");
                addEdge("Chris", "Daniel");
                addEdge("Chris", "Jennifer");
                addEdge("Chris", "Jessica");
                addEdge("Chris", "Matthew");
                addEdge("Chris", "Nicole");
                addEdge("Chris", "Ryan");
                addEdge("Chris", "Elizabeth");
                addEdge("Chris", "Kevin");
                addEdge("Jessica", "Mark");
                addEdge("Jessica", "Rob");
                addEdge("Jessica", "Maria");
                addEdge("Jessica", "John");
                addEdge("Jessica", "Emily");
                addEdge("Jessica", "David");
                addEdge("Jessica", "Sarah");
                addEdge("Jessica", "Michael");
                addEdge("Jessica", "Laura");
                addEdge("Jessica", "Daniel");
                addEdge("Jessica", "Jennifer");
                addEdge("Jessica", "Matthew");
                addEdge("Jessica", "Nicole");
                addEdge("Jessica", "Ryan");
                addEdge("Jessica", "Elizabeth");
                addEdge("Jessica", "Kevin");
                addEdge("Matthew", "Mark");
                addEdge("Matthew", "Rob");
                addEdge("Matthew", "Maria");
                addEdge("Matthew", "John");
                addEdge("Matthew", "Emily");
                addEdge("Matthew", "David");
                addEdge("Matthew", "Sarah");
                addEdge("Matthew", "Michael");
                addEdge("Matthew", "Laura");
                addEdge("Matthew", "Daniel");
                addEdge("Matthew", "Jennifer");
                addEdge("Matthew", "Nicole");
                addEdge("Matthew", "Ryan");
                addEdge("Matthew", "Elizabeth");
                addEdge("Matthew", "Kevin");
                addEdge("Nicole", "Mark");
                addEdge("Nicole", "Rob");
                addEdge("Nicole", "Maria");
                addEdge("Nicole", "John");
                addEdge("Nicole", "Emily");
                addEdge("Nicole", "David");
                addEdge("Nicole", "Sarah");
                addEdge("Nicole", "Michael");
                addEdge("Nicole", "Laura");
                addEdge("Nicole", "Daniel");
                addEdge("Nicole", "Jennifer");
                addEdge("Nicole", "Ryan");
                addEdge("Nicole", "Elizabeth");
                addEdge("Nicole", "Kevin");
                addEdge("Ryan", "Mark");
                addEdge("Ryan", "Rob");
                addEdge("Ryan", "Maria");
                addEdge("Ryan", "John");
                addEdge("Ryan", "Emily");
                addEdge("Ryan", "David");
                addEdge("Ryan", "Sarah");
                addEdge("Ryan", "Michael");
                addEdge("Ryan", "Laura");
                addEdge("Ryan", "Daniel");
                addEdge("Ryan", "Jennifer");
                addEdge("Ryan", "Elizabeth");
                addEdge("Ryan", "Kevin");
                addEdge("Elizabeth", "Mark");
                addEdge("Elizabeth", "Rob");
                addEdge("Elizabeth", "Maria");
                addEdge("Elizabeth", "John");
                addEdge("Elizabeth", "Emily");
                addEdge("Elizabeth", "David");
                addEdge("Elizabeth", "Sarah");
                addEdge("Elizabeth", "Michael");
                addEdge("Elizabeth", "Laura");
                addEdge("Elizabeth", "Daniel");
                addEdge("Elizabeth", "Jennifer");
                addEdge("Elizabeth", "Kevin");
                addEdge("Elizabeth", "Nicole");
                addEdge("Elizabeth", "Ryan");




                break;


            default:
                System.out.println("Opción no válida");
                break;
        }

    }

    /**
     * Check if there is an edge between two vertices.
     *
     * @param label1 the first vertex name.
     * @param label2 the second vertex name.
     *
     * @return true if there is an edge between the two vertices, false otherwise.
     */
    public boolean hasEdge(String label1, String label2) {
        Vertex v1 = vertices.get(label1);
        Vertex v2 = vertices.get(label2);
        return v1 != null && v2 != null && v1.isAdjacent(v2);
    }

    /**
     * Get the graph vertices.
     *
     * @return the graph vertices.
     */
    public Map<String, Vertex> getVertices() {
        return vertices;
    }
}